### ISSUE TITLE
Handle patchy networks and display our own error instead of the Dinosaur

### ISSUE THREAD

**Issue by asavin** [redbadger/website-honestly#104]
![giphy 7](https://cloud.githubusercontent.com/assets/487468/19642445/3812f5ec-99dd-11e6-8c41-97a3c9637511.gif)

When network is patchy and RB site has already loaded at least once, we should be able to take over the network errors and display our own error page with navigation instead of letting it fail into the browser's own empty page.

**Comment by lpil** [comment]
-1
I love the dinosaur

**Comment by tabazevedo** [comment]
Closing as this was handled in https://github.com/redbadger/website-honestly/pull/223
