### ISSUE TITLE
Deploying assets

### ISSUE THREAD

**Issue by asavin** [redbadger/website-honestly#147]
Currently each time we deploy assets, old assets are preserved in the same folder.

<img width="154" alt="s3_aws_red_badger" src="https://cloud.githubusercontent.com/assets/487468/19938570/4fdb0664-a11d-11e6-82b1-d93fcf492af3.png">

**Comment by lpil** [comment]
This is by design. It means we can roll back without recompiling assets.

**Comment by Roisi** [comment]
can this be closed @lpil @asavin ?

**Comment by lpil** [comment]
I think so. :)
