### ISSUE TITLE
Missing Page Titles

### ISSUE THREAD

**Issue by jonsharratt** [redbadger/website-honestly#157]
Loving the new direction!

Noticed there are missing page titles for each new page deployed, title is "Red Badger":

| URL | Page | Current Title |
|-----|---|-----|
https://red-badger.com/ | Home Page | Red Badger |
https://red-badger.com/what-we-do/ | What we do | Red Badger |

Leads to `Back Button` nav not being clear where you are.  Additionally may effect the listing of pages in Google.

**Comment by Roisi** [comment]
🌈 🏭
