### ISSUE TITLE
Lean slice content updates

### ISSUE THREAD

**Issue by Roisi** [redbadger/website-honestly#160]
title should read  - "How do we do the thing right?"

**Comment by clmntnbrn** [comment]
Also on the points on the Lean slice, could the font be all Proxima Nova 16px with the strong class being Proxima Nova bold :)

<iframe src="//giphy.com/embed/l0HlCDFdElciAwpJS" width="480" height="270" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="http://giphy.com/gifs/pgtips-l0HlCDFdElciAwpJS">via GIPHY</a></p>

**Comment by zoeabryant** [comment]
Live now
