### ISSUE TITLE
Icons not displaying on blog

### ISSUE THREAD

**Issue by lithin** [redbadger/website-honestly#167]
Go to red-badger.com/blog
Scroll to the end of an article or to the footer
Icons are displayed as letters

Problem - icon font has been deleted on website old

**Comment by asavin** [comment]
There is a CORS related issue that prevents webfonts from red-badger.com to load on the blog. The fix could be to allow access to red-badger.com on `http` or to move blog to `https`.

**Comment by Roisi** [comment]
dupe of #155 so closing
