### ISSUE TITLE
Open page (background content) shouldn't be scrollable when mobile nav is open

### ISSUE THREAD

**Issue by zoeabryant** [redbadger/website-honestly#171]
- [ ] users shouldn't be able to scroll background content

- [ ] screen reader users shouldn't be able to read background content

**Comment by sarigriffiths** [comment]
Is this same as #197 and #198 but for the Honestly? @samsmith1983 - please fix.

**Comment by samsmith1983** [comment]
I'm not sure this is the same thing (repro steps are a bit scarce!) . 

I think this issue refers to when the mobile nav is open - it's saying that users shouldn't be able to then scroll through the content in the background (ie. the open page), and screen readers shouldn't be able to see the open page.

**Comment by samsmith1983** [comment]
This is mainly fixed in #323. However I've split the screen reader bug into a separate issue, and also logged another improvement issue:

Mobile nav menu should be scrollable #324
Open page (background content) shouldn't be screen-readable when mobile nav is open #325

**Comment by samsmith1983** [comment]
Should have closed this one... The main issue ("Open page (background content) shouldn't be scrollable when mobile nav is open") is now fixed. Remaining issues are logged separately.
