### ISSUE TITLE
missing assets path linked in an old idea

### ISSUE THREAD

**Issue by Roisi** [redbadger/website-honestly#173]
One of the old ideas had a link to a pdf that no longer exists. This may have got lost in the migration so we should try and find it:

https://red-badger.com/ideas/choosing-the-right-way-to-go-mobile/

the link is:

http://red-badger.com/pdf/fact-sheets/Red-Badger-Responsive-Web-Design-Factsheet.pdf

**Comment by asavin** [comment]
https://drive.google.com/file/d/0B0xlwGMZXlw8Y1B6ZjZxb3dkb00/view?usp=sharing
