### ISSUE TITLE
Shouldn't be passing unverified content from the api from the client

### ISSUE THREAD

**Issue by zoeabryant** [redbadger/website-honestly#176]
As discussed here- https://github.com/redbadger/website-honestly/pull/175#discussion_r86569922

- If `CONTACT_US_EMAIL_TO` env var isn't set
- when you try and use the mailing list (unrelated functionality, except they are both lambdas)
- it puts an internal error on the screen (`CONTACT_US_EMAIL_TO environment variable not set!`)

We should make sure we don't pass unverified content from the API to the client - client should get validation errors, other errors should be thrown and logged.

**Comment by lpil** [comment]
Ideally the server would return a success or error type. This can be matched upon to supply the text. The backend doesn't need to know anything about front end copy.

**Comment by Roisi** [comment]
@asavin another one for you to check

**Comment by asavin** [comment]
@Roisi it's a valid issue, basically better error handling when trying to use Contact Us slice and lambda fails. Not a critical one, but would be nice to address it at some point.

**Comment by dpiatek** [comment]
Contact us form is no longer used
