### ISSUE TITLE
tel attribute on phone numbers doesnt provide great UX on desktop

### ISSUE THREAD

**Issue by Roisi** [redbadger/website-honestly#181]
the click to call "tel" attribute on the badger phone number means that it will try to call no matter what device you are on. This leads to issues where instead of being able to copy and paste the phone number, it will do something like open facetime on desktop

<img width="360" alt="screen_shot_2016-11-08_at_14 31 08_720" src="https://cloud.githubusercontent.com/assets/8049847/20104291/58e827ee-a5c5-11e6-98c7-92f77a5c884f.png">

**Comment by sarigriffiths** [comment]
I believe, users have to make this the standard behaviour for tel: links in the first place. So let's leave it for now.

**Comment by Roisi** [comment]
will close this unless it comes up again
