### ISSUE TITLE
HTTP -> HTTPS Forwarding: Google Blog Results

### ISSUE THREAD

**Issue by jonsharratt** [redbadger/website-honestly#184]
## Issue
Blog search results for Google are currently are listed as http urls.  Upon clicking these links you visit the page with a whole heap of SSL errors.

## Reproduction Steps
1. Search Google for `strange loop red badger`
2. Click on top link result (`StrangeLoop 2016 - Red Badger`)
3. End up on `http://red-badger.com/blog/2016/11/07/strangeloop-2016/` instead of https

## Result
![image](https://cloud.githubusercontent.com/assets/430934/20175412/8366647e-a73a-11e6-8973-0b3b742c2d0c.png)

## Suggestion
Setup http -> https forwarding so resolves any requests going via http.  May also help some blog post images that are served under http in WordPress posts when accessed on https (Mixed Content Error).

**Comment by asavin** [comment]
Thanks - we're actually addressing this issue as we speak by abandoning old Wordpress blog and migrating to Squarespace, which is going to be https only.
