### ISSUE TITLE
Hide non-functional elements on homepage when JS is disabled

### ISSUE THREAD

**Issue by asavin** [redbadger/website-honestly#187]
When JS is disabled or not supported on client, it is impossible to sign up for a newsletter or contact us using forms. Instead we're displaying extra info.

We should hide non-functional elements if JS is disabled and provide direct instructions instead.

<img width="396" alt="home___red_badger" src="https://cloud.githubusercontent.com/assets/487468/20221317/c30e1786-a828-11e6-99f5-a75aad235198.png">

<img width="460" alt="home___red_badger" src="https://cloud.githubusercontent.com/assets/487468/20221344/ddfccfb0-a828-11e6-9596-efec57a8f92f.png">

**Comment by zoeabryant** [comment]
in response to @lpil 's message on slack
>  There's a trick, put a style tag inside a noscript tag and have it define a class that does display none
I think this will cause a problem when using the site keyboard only - interactive elements hidden visually are still tabbable. A HTML5 `hidden` attribute is needed. This is not applicable for screen readers, [as most have js](http://a11yproject.com/posts/myth-screen-readers-dont-use-javascript/) , but it is a problem for keyboard only users.

**Comment by lpil** [comment]
Is there a way to avoid that? I can't think of anything that works without JS.

**Comment by zoeabryant** [comment]
I'm not sure there is a solution that doesn't involve changing the markup (& therefore probably use JS). It'd be good to know some stats - the subset of people that have JS turned off and don't use a mouse is possibly not significant.
I'll let you know if I think of anything! @lpil

**Comment by lpil** [comment]
My kingdom for a `<nonoscript>`

**Comment by gregdorward** [comment]
Could we use the "aria-hidden" tag when JS is disabled, so that a screen reader ignores these elements? I think the "hidden" attribute is supported by a lot of screenreader, but not all. Further reading material here - https://www.paciellogroup.com/blog/2013/11/html5-accessibility-chops-hidden-aria-hidden-support/

**Comment by lpil** [comment]
So have it on the first render and then remove it afterwards with JS?

**Comment by gregdorward** [comment]
I hadn't really thought through the implementation, but that sounds like an option, as long as it doesn't block the rendering of the page

**Comment by lpil** [comment]
What were you thinking of? Can't put them on with JS because there's no JS :)

**Comment by lpil** [comment]
Nevermind me, I misread. :)

**Comment by dpiatek** [comment]
Migrating to trello as a fly-by task
