### ISSUE TITLE
accessibility - tenon check

### ISSUE THREAD

**Issue by zoeabryant** [redbadger/website-honestly#192]
Hi team, I've just trialled out a tool called tenon, that we are thinking of using on my current project.
It's flagged a few interesting points about the homepage that can be read in more detail in the report here: https://tenon.io/testNow.php?url=https://red-badger.com/

I suggest the following fixes:

- [ ] Cain/Contact us slice: flags 'This form element has no label.' The input box should an `id` attribute as well as `name` linked to the label [as per this example](http://webaim.org/techniques/forms/controls) 
I initially disregarded this as a false negative as I didn't realise the `for` attribute was linked to the `id` not the `name`!

- [ ] social media links in the footer: flag `This link has no text inside it.` because the link is an svg. Unfortunately this tool doesn't pick up that the svg has a title attribute as an alt text. It seems that VoiceOver does. A quick fix would be using [.visuallyHidden](https://github.com/redbadger/website-honestly/blob/master/site/css/_accessibility.css#L11) to put in the alt text instead. We had agreed that using the built in SVG title functionality was preferable to adding extra markup, but if this tool doesn't pick that up it may be worth revisiting that decision.

- [ ] various SVGs: flag `This id is being used more than once.` we should strip out these ids as part of our assets compression task - I don't see any point to keeping them. It looks like svgo has a flag called `cleanupIDs` for this purpose.

It would be good to run this task for the other website honestly pages as well :)

🎈

also - woo at the
### 94.6% 
pass rate!!

**Comment by asavin** [comment]
Nice one!

**Comment by AndrewBestbier** [comment]
Thanks Zoe! :)

**Comment by gregdorward** [comment]
A few more reports for other pages to add to this one

https://www-staging.red-badger.com/about-us - https://goo.gl/LLX6aw

A high level of id re-use on this one. The more severe issue seems to be around empty buttons, such as in the "previous" and "next" buttons, which could cause issues with people using screen readers. As with the homepage, the contact us forms have no label associated, so are not read out when using a screen reader

https://www-staging.red-badger.com/blog/ - https://goo.gl/qRTLda

A bit of a theme on the blog page is that we're missing alt descriptions of images on the page, which means that a visually impaired user would not know what each image conveys. Also, we need to add in link text for the individual blog posts, as the user wouldn't know what each one discusses

https://www-staging.red-badger.com/about-us/events/ - https://goo.gl/RUwoD5
https://www-staging.red-badger.com/what-we-do - https://goo.gl/CfGmXS

A good result from these pages, with only a couple of common issues, like id re-use and missing link text in our social media links

**Comment by gregdorward** [comment]
Depending on the results of a new run I intend to execute, I may end up closing this one and raising a more up to date ticket

**Comment by gregdorward** [comment]
superseded by #469 - closing this one
