### ISSUE TITLE
[Blog] Some Images Missing

### ISSUE THREAD

**Issue by JoeStanton** [redbadger/website-honestly#196]
I haven't had a chance to check through all my posts, but this one has images missing...
https://red-badger.com/blog/2015/04/27/tech-round-table-2015

Thanks :-)

(via @StuartHarris)

**Comment by JoeStanton** [comment]
This looks like HTTPS mixed content issues. The images are (weirdly) downloaded with `fetch`, so just error instead of warning. Probably an easy fix.

**Comment by lpil** [comment]
> The images are (weirdly) downloaded with fetch

That'll be the service worker. I thought it was a bit weird that it shows up like that

**Comment by JoeStanton** [comment]
Ooh that makes sense
