### ISSUE TITLE
[Blog] A11y: screenreader issues

### ISSUE THREAD

**Issue by JoeStanton** [redbadger/website-honestly#197]
* Nav links are currently listed twice in the list of links
* Potentially improve image link title - it is a post slug currently

![from skitch](https://cloud.githubusercontent.com/assets/487468/20623175/4311f7e2-b2fe-11e6-89f5-d85caea8244a.jpg)

**Comment by asavin** [comment]
Belongs to https://github.com/redbadger/blog-squarespace-template

**Comment by sarigriffiths** [comment]
Fix this please.

**Comment by samsmith1983** [comment]
This is now fixed.

**Comment by samsmith1983** [comment]
Actually when I say fixed, I mean that the menu item duplication issue is fixed.

The image link title issue is not. I'll get another issue logged for that.
