### ISSUE TITLE
[Blog] A11y: tab navigation issues

### ISSUE THREAD

**Issue by JoeStanton** [redbadger/website-honestly#198]
* Currently when tabbing through the landing page the focus goes away into the mobile nav which is hidden. This should be prevented - the same way as it is done on Website Honestly homepage.
* When tabbing through the list of blogs, if the blog has image tab focus goes first onto the image and then on title. Instead title should be focused first.

**Comment by asavin** [comment]
Belongs to https://github.com/redbadger/blog-squarespace-template

**Comment by samsmith1983** [comment]
The first issue was not reporoducile anymore. The second issue is fixed in redbadger/blog-squarespace-template#49
