### ISSUE TITLE
[Events] Upcoming events link to a bad URL

### ISSUE THREAD

**Issue by tabazevedo** [redbadger/website-honestly#199]
When you click on an upcoming event it will lead you to about-us/news instead of about-us/events, which is a dead link.

![image](https://cloud.githubusercontent.com/assets/1136009/20672862/a77b4dae-b57a-11e6-8d54-92b0e0261884.png)

Issue persists with the updated design.

**Comment by asavin** [comment]
Not an issue anymore as we changed design of the event page not to include upcoming events list
