### ISSUE TITLE
Navigation items not matching 

### ISSUE THREAD

**Issue by Monikamu** [redbadger/website-honestly#200]
### Navigation items don't match between different sites:
<img width="732" alt="screen shot 2016-11-28 at 13 55 46" src="https://cloud.githubusercontent.com/assets/16961478/20670771/76053ae4-b572-11e6-9a6f-652b5691011e.png">

Can we please have those items in this order:

1. Home https://red-badger.com/
2. What we do https://red-badger.com/what-we-do/
3. About us https://red-badger.com/about-us/
4. Blog https://red-badger.com/blog/
5. Events https://red-badger.com/about-us/events/

**Comment by tabazevedo** [comment]
Closing as this was fixed.
