### ISSUE TITLE
Fix image displayed when sharing any content.

### ISSUE THREAD

**Issue by tabazevedo** [redbadger/website-honestly#201]
Sharing a vacancy page shows a cropped Red Badger header, whereas sharing a normal page shows a cropped badger logo, need to clarify at some point with @Monikamu and @sarigriffiths and show a properly formatted image depending on what we are sharing.

<img width="497" alt="screen shot 2016-11-28 at 15 48 56" src="https://cloud.githubusercontent.com/assets/1136009/20675739/38e8cec4-b585-11e6-872f-1449fdcbf5ed.png">

<img width="505" alt="screen shot 2016-11-28 at 16 08 51" src="https://cloud.githubusercontent.com/assets/1136009/20675743/3a63a22e-b585-11e6-9b4e-976013db4ba4.png">

Previously it was blank due to a bug: https://github.com/redbadger/website/issues/53

**Comment by asavin** [comment]
`og:image` seems to be missing from our Jobs and Events pages

**Comment by sarigriffiths** [comment]
Has this been sorted? @asavin

**Comment by Roisi** [comment]
@samsmith1983 to check and add to board if still present

**Comment by samsmith1983** [comment]
This is still happening. However, this join us page now gives a blank image:

![screen shot 2017-01-17 at 15 13 54](https://cloud.githubusercontent.com/assets/22592849/22026057/95125738-dcc7-11e6-8292-3f8c2123f863.png)

**Comment by samsmith1983** [comment]
Added to board

**Comment by dstodolny** [comment]
The website has to be scraped again in facebook graph debugger when the any of the graph tag change. https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fred-badger.com%2Fabout-us%2Fjoin-us%2F
I did that and now it displays big Red Badger logo, however it's sliced

**Comment by samsmith1983** [comment]
This is now fixed
