### ISSUE TITLE
Enhancement: Add custom icons for devices

### ISSUE THREAD

**Issue by tabazevedo** [redbadger/website-honestly#202]
Following a discussion about custom icons for iPhone, iPad & Android. It would be nice to have some pretty icons, when Blanca has the time.

More on this: http://www.kylejlarson.com/blog/2013/adding-an-icon-for-iphone-ipad-android-to-your-website/

Migrated from https://github.com/redbadger/website/issues/310

**Comment by dpiatek** [comment]
This was done
