### ISSUE TITLE
[Docpad] Image folder does not get updated properly when published

### ISSUE THREAD

**Issue by tabazevedo** [redbadger/website-honestly#203]
See https://github.com/redbadger/website/issues/54

I imagine this issue still exists, but will be fixed once everything from Docpad is moved to our new pipeline, so I'm going to move this here just so we're aware.

**Comment by gregdorward** [comment]
Cannot access original issue, so unable to verify if this is still a bug

**Comment by grahammendick** [comment]
@gregdorward i don't think the docpad website exists anymore. Can we close this?

**Comment by dpiatek** [comment]
Docpad is 💀
