### ISSUE TITLE
Tags on website-old create broken links

### ISSUE THREAD

**Issue by Monikamu** [redbadger/website-honestly#205]
Tags in 'tell me more' section on the website-old result in broken links. 
Can we remove them? 
<img width="713" alt="screen shot 2016-11-29 at 14 23 22" src="https://cloud.githubusercontent.com/assets/16961478/20713250/6b6ac20c-b63f-11e6-8b93-622ec3d639f9.png">

Those links appear at the bottom of all our case studies, e.g. https://red-badger.com/our-work/case-study/financial-times/

**Comment by AndrewBestbier** [comment]
Can do. Will pick it up
