### ISSUE TITLE
[Blog] Listing page title design change

### ISSUE THREAD

**Issue by Monikamu** [redbadger/website-honestly#208]
### What is the problem?
On blog listing page: https://blog.red-badger.com/ the titles are on a large size and the underline on hover touches the text below.

### Can we:

- [ ] drop the font size to M2 (30px) (ref: http://brand.red-badger.com/d/WEl30uS4YzKw/red-badger-styleguide-style-guide#/elements/typography)
- [ ] move the underline up by a few pixels

**Comment by dstodolny** [comment]
Linked PR: https://github.com/redbadger/blog-squarespace-template/pull/43

**Comment by samsmith1983** [comment]
^ This is now fixed
