### ISSUE TITLE
PageSpeed - Optimize CSS Delivery

### ISSUE THREAD

**Issue by asavin** [redbadger/website-honestly#222]
Google PageSpeed recommends loading CSS in a non-blocking way. There are multiple ways of improving our score:

`https://hello.myfonts.net/count/322627` - there's an alternative way of embedding the fonts by using a non-blocking script

`https://red-badger.com/assets-honestly/styles-1H0IY.css` - we could separate critical styles for initial pageload and inline them on the page, while loading rest of styles later.

**Comment by gregdorward** [comment]
Some PSI changes have been applied by Etiene in #361, but having just ran a new test on the homepage, it still suggests we have an issue with render-blocking JavaScript

**Comment by grahammendick** [comment]
@gregdorward your comment refers to render-blocking JavaScript but this issue is about render-blocking CSS. Can you run the test again and see if it grumbles about the CSS (and fonts)?

**Comment by gregdorward** [comment]
If we manage to get #455 through, that should take care of this one. This is ultimately a UX/Design decision though
