### ISSUE TITLE
Service worker caching

### ISSUE THREAD

**Issue by tabazevedo** [redbadger/website-honestly#231]
After the introduction of https://github.com/redbadger/website-honestly/pull/227 we now have a 'dynamic' route in the app and the service worker is trying to cache the URL `/about-us/join-us/{slug}`, which obviously fails. We need to discuss exactly what pages to cache and if we want to run `makeRoutes()` and cache all the dynamically generated stuff in the background too.

**Comment by asavin** [comment]
<img width="1427" alt="screen shot 2016-12-12 at 16 04 09" src="https://cloud.githubusercontent.com/assets/487468/21106260/6302e4fa-c085-11e6-82ab-6e79e1c225d3.png">

Seems like the same issue we're now experiencing in prod. The solution for now would be I suppose not to let service worker cache dynamic routes.

**Comment by asavin** [comment]
On the second thought, the above mentioned issue might be because of the forward slash missing from the `join-us` route.

**Comment by asavin** [comment]
This issue is resolved for now by stopping SW from prefetching any page
