### ISSUE TITLE
[Blog] Chrome fetches 3 different favicons

### ISSUE THREAD

**Issue by asavin** [redbadger/website-honestly#233]
<img width="886" alt="home___red_badger" src="https://cloud.githubusercontent.com/assets/487468/21017780/77f7548e-bd62-11e6-970f-a15bfd0432ea.png">

As reported by @StuartHarris 

Should probably be reduced to one?

**Comment by Etiene** [comment]
I'll investigate into this

**Comment by samsmith1983** [comment]
This is fixed in the main site, but still happens on the blog page. Reopening.

**Comment by samsmith1983** [comment]
Added [Blog] keyword to summary

**Comment by gregdorward** [comment]
I can't reproduce this one on any of the Honestly site pages, including the blog @Roisi . See attached screenshot
<img width="1280" alt="screen shot 2017-02-13 at 15 57 23" src="https://cloud.githubusercontent.com/assets/20296527/22890864/7c8e0984-f205-11e6-99b4-660cddac94bd.png">

**Comment by gregdorward** [comment]
Closing, as cannot reproduce
