### ISSUE TITLE
Map pin is slightly off

### ISSUE THREAD

**Issue by asavin** [redbadger/website-honestly#279]
As reported by @ranjith0 - when you click on "Open in Google Maps" link on footer, you get a map pin which is slightly misleading.

<img width="290" alt="ec1y_8rq_-_google_maps" src="https://cloud.githubusercontent.com/assets/487468/21307831/20d6ccf0-c5cf-11e6-890e-2a7b14d7bf5c.png">

The link should be this instead https://www.google.com/maps/place/12+Mallow+St,+London+EC1Y+8RQ,+UK/@51.52477,-0.0908016,17z/data=!3m1!4b1!4m5!3m4!1s0x48761ca8a59bf3b3:0x4cdb7444be05c280!8m2!3d51.52477!4d-0.0886129?hl=en

**Comment by Etiene** [comment]
* Is the data parameter really necessary? 
* Should we use google.co.uk instead of google.com?

**Comment by Etiene** [comment]
The blue dot of `my location` changes to a weird location if I leave your data parameter intact and will position differently when it's removed.  

<img width="380" alt="screen shot 2016-12-22 at 17 27 21" src="https://cloud.githubusercontent.com/assets/1516418/21434382/0c3db08e-c86c-11e6-9051-2bf1259554ef.png">

<img width="328" alt="screen shot 2016-12-22 at 17 27 27" src="https://cloud.githubusercontent.com/assets/1516418/21434385/126f37ac-c86c-11e6-95e6-5ec4f1ef3df3.png">

**Comment by sarigriffiths** [comment]
Please use the link Alex provided. @samsmith1983
