### ISSUE TITLE
Events page doesn't show event details on iOS 8 (and earlier)

### ISSUE THREAD

**Issue by samsmith1983** [redbadger/website-honestly#281]
On iOS 8 and earlier, the events page doesn't show event details:

![screen shot 2016-12-19 at 14 00 12](https://cloud.githubusercontent.com/assets/22592849/21315343/a110dd56-c5f3-11e6-8c52-cb065eaa272f.png)

**Comment by samsmith1983** [comment]
We don't "officially" support iOS 8, but this seems bad enough to warrant fixing.

**Comment by sarigriffiths** [comment]
Information shouldn't really disappear. :-(

**Comment by samsmith1983** [comment]
^ This has now been fixed. Closing.
