### ISSUE TITLE
Mobile nav menu is not shown on iOS 8 or earlier

### ISSUE THREAD

**Issue by samsmith1983** [redbadger/website-honestly#282]
Mobile nav menu is not shown on iOS 8 or earlier:

![screen shot 2016-12-19 at 14 17 37](https://cloud.githubusercontent.com/assets/22592849/21315840/e9fd6faa-c5f5-11e6-97d6-33503947e23f.png)

**Comment by dstodolny** [comment]
I'm not seeing this issue anymore. Can anyone confirm?

**Comment by samsmith1983** [comment]
@dstodolny still happens for me! I'm using the iPhone 6S device on browserstack.
