### ISSUE TITLE
Trying to sign up for newletter on old pages blows up with 404

### ISSUE THREAD

**Issue by samsmith1983** [redbadger/website-honestly#284]
Trying to sign up newsletter on old style page, eg this one:
https://red-badger.com/about-us/people/andreas-conradi/

Tries to take you to this page:
https://red-badger.com/newsletter/signup/

Which does not exist

**Comment by asavin** [comment]
Needs UX assessment, but I suppose we could remove newsletter sign up from the old footer completely.

**Comment by samsmith1983** [comment]
This is now fixed (see above PR)
