### ISSUE TITLE
Nasty error when clicking on some links with no web connection (on firefox)

### ISSUE THREAD

**Issue by samsmith1983** [redbadger/website-honestly#285]
With the addition of service workers, i _think_ this should work:

- Go to home page
- Turn off wifi
- Click on "3: number of awards for the new online store (fortnum and mason)" link
- I get this in Firefox:

![screen shot 2016-12-19 at 15 05 59](https://cloud.githubusercontent.com/assets/22592849/21317444/01d259cc-c5fd-11e6-912f-354d7a2c883d.png)

**Comment by asavin** [comment]
To clarify - this only happens on pages which are not cached. The expected behaviour is to redirect to a special "no internet" page, which works on Chrome but fails on Firefox.

**Comment by samsmith1983** [comment]
@asavin I get this on Chrome, so possibly isn't unique to firefox:

![screen shot 2016-12-20 at 14 45 05](https://cloud.githubusercontent.com/assets/22592849/21354704/0b2bbd3a-c6c3-11e6-8914-f4d91149d527.png)

**Comment by JoeStanton** [comment]
@samsmith1983 do you get console errors on Chrome when this happens? It was working.

**Comment by asavin** [comment]
To clarify more - this only happen on `www` url:s. There's related issue to implement permanent redirects for `www` url:s #294 

There's another issue which is specific to Firefox:
https://stackoverflow.com/questions/40274429/corrupted-content-error-on-firefox-with-polymer-firebase/40277730#40277730

The offline page doesn't get displayed properly by Firefox, and that needs fixing.

**Comment by sarigriffiths** [comment]
I agree that error looks pretty scary for non-tech person.
Could someone take a look and see how easy is it to fix this? 
FYI We have about 6-7% visitors using Firefox.

**Comment by gregdorward** [comment]
Still an issue, as described originally

**Comment by grahammendick** [comment]
The fix in #400 would also solve this
