### ISSUE TITLE
[Commit Preview Site] - Link Inconsistency

### ISSUE THREAD

**Issue by JoeStanton** [redbadger/website-honestly#291]
There are a number of links not rendered via the `<Link>` component. These links don't preserve the `/:sha/:path` format required by the preview proxy and therefore end up routing the user to the `master` preview.

This is very confusing during on branch testing, so we need to move all `<a>` to `<Link>` except external links.

**Comment by asavin** [comment]
Blog should be considered an external link

**Comment by JoeStanton** [comment]
cc/ @samsmith1983

**Comment by sarigriffiths** [comment]
Should this be high priority @JoeStanton?

**Comment by samsmith1983** [comment]
Setting this to Medium priority. It would be awesome for me for testing purposes, but nobody else will get any benefit :)

**Comment by samsmith1983** [comment]
Closing this as it's fixed in the people page branch. The only remaining links that don't take you to the preview site are the ones to the blog or the old site (or other external links).
