### ISSUE TITLE
Blog text style: Add 10px margin above bullet points

### ISSUE THREAD

**Issue by sarigriffiths** [redbadger/website-honestly#301]
Space is tight. Add 10px as par paragraph tag.
<img width="460" alt="screenshot 2016-12-22 17 00 14" src="https://cloud.githubusercontent.com/assets/3176873/21433611/64132720-c868-11e6-92de-8fd91608cce1.png">

**Comment by sarigriffiths** [comment]
It will be good if this gets fixed. 
Shall we make an issue with all design fix? 
@samsmith1983

**Comment by samsmith1983** [comment]
@sarigriffiths  what are the other design issues that need fixing?

**Comment by samsmith1983** [comment]
^ This is now fixed.
