### ISSUE TITLE
Numbers in case studies on homepage are not centred on MS Edge

### ISSUE THREAD

**Issue by samsmith1983** [redbadger/website-honestly#302]
Using MS Edge 14. The issue is more apparent at narrower widths:

![screen shot 2016-12-23 at 11 26 13](https://cloud.githubusercontent.com/assets/22592849/21452994/e44bd4ce-c902-11e6-9cfa-d004eb3ab63e.png)

**Comment by sarigriffiths** [comment]
It's 1% of our user base and they are not losing info, so it's a minor problem.
