### ISSUE TITLE
Favicon occasionally not loading on IE11

### ISSUE THREAD

**Issue by samsmith1983** [redbadger/website-honestly#307]
This seems to be intermittent, and is possibly related to #283.

To repro:

- Open IE11
- Go to redbadger.com
- Click on 'what we do'

For me, about 50% of the time the favicon does not appear.

**Comment by dstodolny** [comment]
This is related with a bug in IE11 itself https://connect.microsoft.com/IE/feedback/details/1008701/when-doing-a-history-pushstate-internet-explorer-doesnt-account-for-the-base-tag-for-the-favicon. Unfortunately the status of the bug is: Won't Fix :(

**Comment by samsmith1983** [comment]
Closing this as we can't / won't fix it.
