### ISSUE TITLE
[BLOG] When publishing a blog, then changing the title, publishing again, then changing the URL, blog explodes

### ISSUE THREAD

**Issue by asavin** [redbadger/website-honestly#312]
Currently there seems to be an issue with Squarespace blog when you do following things:

* Publish a blog
* Decide to change its title - Squarespace automatically updates slug of the URL
* Decide that you want to keep the original URL of the blog and manually edit the URL in blog options
* --> That results in the blog preview exploding, and index page of the blog doesn't reflect correct updated URL of the blog

Needs either user documentation update to say that once the blog is published you are not allowed to change the blog title, or keep in mind that Squarespace will change the URL of the blog when you do change the title - this means updating blog URL:s in the social media posts.

This is all a bit 💩 tbh, need to check if there's ongoing issue with the Squarespace itself.

**Comment by asavin** [comment]
Some more details on this one:

* You can publish a blog and change title later - Squarespace doesn't change the URL
* If you decide to change that already published URL manually, you will get an error in the blog preview
* If after that you reload the whole Squarespace it seems to recover fine, and URL is updated
* Old URL however will stop working and you have to implement a redirect yourself - there is a way of doing that inside Squarespace https://support.squarespace.com/hc/en-us/articles/205815308

**Comment by asavin** [comment]
Resolution to this issue would be to communicate to our blog users not to change URL of the blog once it is published.

**Comment by Etiene** [comment]
In case a renaming must absolutely be done, I suggest this is handled by an engineer. It would be useful to link this squarespace guide on redirect somewhere internally on our docs, so future people will know how to address this in case it's needed.

**Comment by asavin** [comment]
Yes, there's also a way to create redirects directly on Squarespace if needed

**Comment by asavin** [comment]
@samsmith1983 i'd say we should remove the High label

**Comment by samsmith1983** [comment]
@asavin i'll remove it and not replace it, then we can discuss in one of our upcoming bug triage sessions 😀
