### ISSUE TITLE
[Blog] text too large on pagination buttons

### ISSUE THREAD

**Issue by sarigriffiths** [redbadger/website-honestly#318]
<img width="537" alt="screenshot 2017-01-05 16 23 44" src="https://cloud.githubusercontent.com/assets/3176873/21688107/889dbcda-d363-11e6-8d8b-491a7c988d4e.png">

These are 30px but I think it should be 24px as par homepage buttons?
They are too big, Next page button wraps on a small screen.

**Comment by sarigriffiths** [comment]
Related visual styling issues: #301 #275 #208

**Comment by samsmith1983** [comment]
This is now fixed.
