### ISSUE TITLE
[Blog] Correct font is not loaded on MS Edge (blog page only)

### ISSUE THREAD

**Issue by samsmith1983** [redbadger/website-honestly#322]
This is what it looks like:

![screen shot 2017-01-06 at 16 19 30](https://cloud.githubusercontent.com/assets/22592849/21724392/0c8756d2-d42c-11e6-9d92-0ab6e60d5c7e.png)

**Comment by samsmith1983** [comment]
0.92% of our recents users are on Edge.

**Comment by asavin** [comment]
Might be a browserstack issue - when I run blog on Virtual Machine Edge 14 it looks fine
<img width="798" alt="screen shot 2017-01-06 at 16 38 43" src="https://cloud.githubusercontent.com/assets/487468/21725079/c0f51fbc-d42e-11e6-9078-9d8e1d19e98f.png">

Can we verify this on actual Windows Edge?

**Comment by asavin** [comment]
On Browserstack it is only failing on Edge 14, looks fine on 13.

**Comment by samsmith1983** [comment]
Works fine in my Edge 14 VM, so does looks likely to be something weird with browserstack. Let's close this.
