### ISSUE TITLE
Mobile nav menu should be scrollable

### ISSUE THREAD

**Issue by samsmith1983** [redbadger/website-honestly#324]
The mobile nav menu should be scrollable. Currently it is not. This happened as a known side effect of the fix for #171 (see PR #323). 

What we need is for the background page not to scroll, but the menu to scroll. This is mainly useful for when in landscape orientation on a mobile, where menu items will be cut off from the nav:

![screen shot 2017-01-09 at 16 33 27](https://cloud.githubusercontent.com/assets/22592849/21774131/636ce8ae-d689-11e6-8752-a0f63b1f7e81.png)

**Comment by gregdorward** [comment]
Still an issue, as originally described

**Comment by grahammendick** [comment]
Also fixed by #380 @samsmith1983 @gregdorward

**Comment by samsmith1983** [comment]
Yep, verified fixed as per testing for #380. Closing.
