### ISSUE TITLE
[Blog] Open page (background content) shouldn't be scrollable when mobile nav is open

### ISSUE THREAD

**Issue by samsmith1983** [redbadger/website-honestly#326]
This is essentially a clone of #171 (which is fixed) but for the blog page.

Repro:

- Grab a mobile or resize to mobile size
- Go to blog page
- Open mobile nav
- Scroll

Background content scrolls when it shouldn't.

**Comment by samsmith1983** [comment]
@sarigriffiths

**Comment by gregdorward** [comment]
Still a valid issue

**Comment by dstodolny** [comment]
This was fixed in: https://github.com/redbadger/blog-squarespace-template/pull/46
