### ISSUE TITLE
Contact us link on old footer should go to homepage footer

### ISSUE THREAD

**Issue by serdemli** [redbadger/website-honestly#327]
The footer on old pages (ie technology, our-work, our-work/case-study/client-name) still has a contact us link. 
Currently it takes you to the top of the homepage. 
It should be taking you to the new footer on the homepage, so the contact information is visible to the reader. 

To replicate, go to any of the links below and click on Contact us from the footer. 
https://red-badger.com/services/technology/
https://red-badger.com/our-work/
https://red-badger.com/our-work/case-study/sky/

**Comment by asavin** [comment]
Alternative option would be Contact Us slice with the form?

**Comment by serdemli** [comment]
Let's keep the footer as the address and other social links are there and
contact us can be used to get that information

**Comment by gregdorward** [comment]
Still a valid issue

**Comment by dpiatek** [comment]
Not an issue anymore
