### ISSUE TITLE
[Blog] Search results preview doesn't work in iOS9

### ISSUE THREAD

**Issue by samsmith1983** [redbadger/website-honestly#330]
This seem to be ok in iOS10 but not in iOS9.

Repro:
- Grab an iOS9 device (or use browserstack)
- Go to /blog
- Type something like "agile" but don't press enter

Nothing happens.

You should see a list of results in a dropdown.

**Comment by asavin** [comment]
Yeah we do not control this functionality, so nothing can be done.

**Comment by samsmith1983** [comment]
@asavin ah ok, will close then 😞
