### ISSUE TITLE
On About us page: Timeline circles are not aligned perfectly on the line

### ISSUE THREAD

**Issue by AndrewBestbier** [redbadger/website-honestly#337]
Hi team!

Just found a potential minor minor minor css error on the site and thought I would make an issue. If it is a confirmed issue I am happy to make a PR for it after work this evening.

If you go here: https://red-badger.com/about-us you see this:

<img width="623" alt="screen shot 2017-01-19 at 10 58 35" src="https://cloud.githubusercontent.com/assets/6062416/22104336/8e8495d2-de36-11e6-8b73-57f0315e9407.png">

Where the circle's centre point is above the line. 

By changing the style on the circle span to: bottom: -1px. It is fixed:

<img width="1418" alt="screen shot 2017-01-19 at 11 02 21" src="https://cloud.githubusercontent.com/assets/6062416/22104398/d4398510-de36-11e6-9203-7eaa7d7d916f.png">

To: 
<img width="633" alt="screen shot 2017-01-19 at 11 03 08" src="https://cloud.githubusercontent.com/assets/6062416/22104408/e205e422-de36-11e6-8994-f5a1f509fd1a.png">

**Comment by asavin** [comment]
Is this Chrome only issue or can you reproduce this on other browsers too?

**Comment by AndrewBestbier** [comment]
Seen on Firefox and Safari too.

**Comment by asavin** [comment]
![](http://i.imgur.com/SdyWDoN.jpg)
Mobile Safari

**Comment by samsmith1983** [comment]
This was fixed in #347
