### ISSUE TITLE
[BLOG] When blog title is long, featured image is shifted to the right

### ISSUE THREAD

**Issue by asavin** [redbadger/website-honestly#348]
**Description of the issue:**

**Browser used:**
Chrome

**OS used:**
MacOS Sierra

**Device used:**
Macbook

**Steps to reproduce:**

1. Open red-badger.com/blog
2. Scroll down until you see a blog with a title long enough to be broken into second line
3. Observe that featured image is shifted to the right compared to other blogs

**Actual result:**

<img width="592" alt="red_badger_blog" src="https://cloud.githubusercontent.com/assets/487468/22252489/492b2a96-e246-11e6-88a5-3de5523d3b58.png">

**Expected result:**

All images are aligned even when blog title is broken into the second line

**Comment by samsmith1983** [comment]
This was fixed in the PR above ^
