### ISSUE TITLE
[BLOG ARTICLE] Listed items need 10px bottom padding

### ISSUE THREAD

**Issue by Monikamu** [redbadger/website-honestly#351]
Lists on our blog page need padding to increase legibility

**Browser used:**
any
**OS used:**
any
**Device used:**
any

**Steps to reproduce:**

1. go to here: https://red-badger.com/blog/2017/1/23/inclusivity-at-react-london-2017

**Actual result:**
padding-bottom: 0px;

**Expected result:**
padding-bottom: 10px;

**Comment by Roisi** [comment]
fixed
