### ISSUE TITLE
Cloudinary images not loading on Android (via BrowserStack ONLY)

### ISSUE THREAD

**Issue by samsmith1983** [redbadger/website-honestly#353]
**Description of the issue:**

This only affects browserstack - not real devices. But it's hindering testing a bit, so would be good to fix if it's something within our control

**Browser used:** Chrome
**OS used:** Android 7
**Device used:** Pixel via Browserstack

**Steps to reproduce:**

1. Open an android device, such as the google pixel, via browserstack
2. Go to /about-us/people

**Actual result:**

None of the profile photos load, and this in console:

![screen shot 2017-01-27 at 15 44 07](https://cloud.githubusercontent.com/assets/22592849/22376835/77514a14-e4a7-11e6-89a4-92f493dc9aaa.png)

**Expected result:**

Should load fine

**Comment by gregdorward** [comment]
@samsmith1983 , do you still have this issue, as it looks ok on mine following your steps to reproduce?

**Comment by samsmith1983** [comment]
@gregdorward seems fine now. Probs was something on their end! 

Closing this.
