### ISSUE TITLE
Browser Back button doesn’t reliably restore the scroll position

### ISSUE THREAD

**Issue by grahammendick** [redbadger/website-honestly#354]
**Description of the issue:**
The browser back button on Google Chrome doesn't always restore the scroll position.

**Browser used:** Google Chrome
**OS used:** Mac
**Device used:** Desktop

**Steps to reproduce:**

1. Go to the [events page](https://red-badger.com/about-us/events)
2. Scroll down the events list and select the 10th event (although, anything greater than the 4th event would probably work)
3. Press the back button

**Actual result:**
You're returned to the wrong place in the events list

**Expected result:**
You're returned to the right place in the events list, showing the selected event again

**Comment by grahammendick** [comment]
Turns out this happens when going back from a shorter page to a longer page. The event details page is shorter than the event list page. Google won’t restore the scroll position if it’s further down than the length of the event details page. That’s why, beyond a certain point in the event list, you’re always taken back to the same point (the length of the event details page). Not sure if it’s the same as this [google chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=423639).


There is a workaround. In the site/client/index.js, before rendering the new component, set the body height to a large number (any number that’s guaranteed bigger than the page height) and cause a reflow (get offsetHeight) so that the change to height is registered. This is enough to restore the scroll position correctly. Then reset the body height.

    stateNavigator.onNavigate((oldRoute, route, params) => {
      …
      document.body.style.height = '999999px';
      document.body.offsetHeight;
      document.body.style.height = '';
      ReactDOM.render(component, element, scrollTo(params));
    });

Should we go with this workaround?

**Comment by asavin** [comment]
Could try if that works. This only occurs when we're in single page app mode.

**Comment by dpiatek** [comment]
Can't replicate this anymore, closing
