### ISSUE TITLE
Footer - Incorrect copyright year.

### ISSUE THREAD

**Issue by chris-brookes** [redbadger/website-honestly#372]
Incorrect copyright date on footer. It needs to be changed to 2017.
See image attached.

![screen shot 2017-02-10 at 14 36 01](https://cloud.githubusercontent.com/assets/9529865/22830411/5ee1abca-ef9e-11e6-93b9-1bfacf9550c4.png)

**Comment by asavin** [comment]
I would argue that the year shouldn't be there at all - copyright is automatically asserted on the content. Year here doesn't serve any purpose. You don't even have to put copyright clause - content is _always_ copyrighted unless told otherwise.

**Comment by chris-brookes** [comment]
@asavin - So what are we going to do here? Who's choice is it?

**Comment by asavin** [comment]
@chris-brookes this has to be a UXD decision

**Comment by gregdorward** [comment]
@sarigriffiths, do you have a preference on what we should do here?

Option 1 - Update it to 2017
Option 2 - Remove the year

It seems like a fairly visible issue, but one that's simple to fix, so we should raise the priority a bit

**Comment by chris-brookes** [comment]
I have changed the date to 2017, and that is how Sari would like it to be done.
