### ISSUE TITLE
Badger profile: Some badgers without signature skills get [object Object] printed on their profile page

### ISSUE THREAD

**Issue by samsmith1983** [redbadger/website-honestly#374]
**Description of the issue:**

If, in prismic, a badger doesn't have any signature skills registered, sometimes (not figured out yet exactly why/when), they get `[object Object]` printed on their profile page

**Browser used:** Chrome
**OS used:** OSX Sierra
**Device used:** Macbook pro

**Steps to reproduce:**

1. Go here: https://www-staging.red-badger.com/59e2feb/about-us/people/joe-paice

**Actual result:**

![screen shot 2017-02-13 at 12 37 41](https://cloud.githubusercontent.com/assets/22592849/22883835/f86b1464-f1e9-11e6-9c14-e1e80f4ccccc.png)

**Expected result:**

Should just not show any signature skills

**Comment by samsmith1983** [comment]
@Etiene

**Comment by grahammendick** [comment]
The Skills used to be a list in Prismic, but it was recently [changed to be a single text entry](https://github.com/redbadger/website-honestly/pull/333#issuecomment-276936925). Prismic doesn’t delete the old data when a field’s updated, so all the badgers still had a list of skills. The list of skills is forced into the single text field when the badger’s returned from Prismic and that causes the `[object Object]` (one for each skill in the old list). To fix it just enter new skills in the text field in Prismic.

**Comment by asavin** [comment]
Yes so as mentioned by @grahammendick this is not an issue
