### ISSUE TITLE
Incorrect button style on what-we-do page

### ISSUE THREAD

**Issue by chris-brookes** [redbadger/website-honestly#378]
On the 'What-we-do' page the buttons 'See more of our work' and 'More about tech' should have a hover over colour #212121 to match the style of buttons on other pages. eg. .../about-us

![screen shot 2017-02-14 at 14 24 09](https://cloud.githubusercontent.com/assets/9529865/22933021/1c77fc72-f2c2-11e6-859c-23e360ebee32.png)

![screen shot 2017-02-14 at 14 24 28](https://cloud.githubusercontent.com/assets/9529865/22933025/2021e66c-f2c2-11e6-846b-50ed68d95e05.png)

![screen shot 2017-02-14 at 14 00 54](https://cloud.githubusercontent.com/assets/9529865/22933033/24d5532e-f2c2-11e6-848b-7b98c3d3cfae.png)

UPDATE - There are more buttons across the home page and the join-us job details pages that have the same incorrect style.

![screen shot 2017-02-14 at 15 20 20](https://cloud.githubusercontent.com/assets/9529865/22935585/e5ac9a50-f2ca-11e6-850f-97f6dfa9d8cd.png)

**Comment by gregdorward** [comment]
I think this also affects other pages, like on the Homepage, the "See more of our work" button also doesn't have a hover state. I'm sure there's more, so we might have to document all these

**Comment by Roisi** [comment]
@gregdorward to do a pass and list which buttons dont have the hover

**Comment by gregdorward** [comment]
The following buttons do not currently have the hover state implemented on the 'Meet our team' and 'Join us' buttons found on the 'About us' page

### Homepage

'See more of our work'
'What we do'
'More about the tech'
'Submit'
'Read our blog'
'Sign up' - in this case the cursor arrow doesn't even transition into a finger icon

### What we do

'More about the tech'
'See more of our work'

### About us

'Submit'

### Blog

'Next page'
