### ISSUE TITLE
Emails not rendering correctly in Gmail (mail.google.com)

### ISSUE THREAD

**Issue by gregdorward** [redbadger/website-honestly#383]
**Description of the issue:**
When opening one the Welcome Journey emails in mail.google.com, there are a couple of fairly major layout issues:

1) In the "We love tech..." email, an entire section displaying the technologies we love is displayed with a white background, rather than black
![img_1407](https://cloud.githubusercontent.com/assets/20296527/23162817/ae21cce2-f827-11e6-9390-dcfc76384ccf.jpg)

2) On Android, this same email is not rendered is a responsive way
![screenshot_20170220-121505](https://cloud.githubusercontent.com/assets/20296527/23162835/c40b196e-f827-11e6-84f6-791f9c750685.png)

@chris-brookes  to update if either of the other two Welcome emails are affected by the same issues on Android

**Browser used:**
Safari
Chrome

**OS used:**
iOS 
Android

**Device used:**
iPhone 6s
Samsung Galaxy S7

**Steps to reproduce:**

1. Log in to Gmail at mail.google.com on either an iPhone or Android phone
2. Trigger the Welcome emails from Mailchimp
3. Check the rendering of the mail content

**Actual result:**
As shown in the attached screenshots, the content is not confined to the width of the screen, and the background colour of a frame is being altered

**Expected result:**
The mail content should be as per the template in Mailchimp

**Additional note**
This content renders correctly in the iOS Gmail app - @chris-brookes will have to verify the Android equivalent app

**Comment by Etiene** [comment]
@gregdorward greg, I could not reproduce this on iOS, tried both safari and chrome. can't try on android!

**Comment by chris-brookes** [comment]
@Etiene @gregdorward 
Android Update - All 3 emails are not displaying correctly on the mobile google mail web site.
1. Thanks for signing up email - The whole email is not changing to the mobile size layout, so half of the email is cut off the screen.

![screenshot_20170220-122300](https://cloud.githubusercontent.com/assets/9529865/23311786/3ab1a72a-faaf-11e6-9f67-ac7ab312a8be.png)

2. We sole complex problems.... email - The main content table is not changing to the mobile size layout and also being cut off the screen. The grey background is also not aligning correctly to the mobile layout.

![screenshot_20170220-122323](https://cloud.githubusercontent.com/assets/9529865/23311793/410cc848-faaf-11e6-9f7f-85532e1bd453.png)


3. The 3rd email issues have already been entered for the android.

**Comment by gregdorward** [comment]
@chris-brookes is this the issue that we can't do anything about, i.e. the issue is on Gmail's side? Just wondering if we can close it?

**Comment by Etiene** [comment]
Most of the problems on this issue were fixed. The remainder issues cannot be fixed.
Source: https://litmus.com/blog/gmail-to-support-responsive-email-design
