### ISSUE TITLE
Emails viewed in browser - Header and footer links should open the pages in new tabs

### ISSUE THREAD

**Issue by chris-brookes** [redbadger/website-honestly#388]
**Description of the issue:**
When viewing the email in a browser, the header and footer links open the pages in the same window and you are directed away from the email page. The links should open the pages on a new tab.

**Browser used:**
All
**Device used:**
Any

**Steps to reproduce:**

1. On the email, click on the link in the top right corner to open the email in a browser.
2. Click on any of the links on the header or footer.

**Actual result:**
The page changes within the same window. 
**Expected result:**
The page from the link should open in a new browser tab, like all the links in the main content do.

![screen shot 2017-02-24 at 18 18 31](https://cloud.githubusercontent.com/assets/9529865/23315390/eaa5e50c-fabd-11e6-89fe-5c7b1c5d771e.png)

![screen shot 2017-02-24 at 18 18 41](https://cloud.githubusercontent.com/assets/9529865/23315426/17e97f24-fabe-11e6-9c19-29ccc655d09e.png)

**Comment by grahammendick** [comment]
@chris-brookes I think the welcome journey's fixed, so can this be closed?

**Comment by gregdorward** [comment]
This one is still an issue

**Comment by gregdorward** [comment]
This is still an issue, but only on mobile within Safari. 

Device - iPhone 6s
OS - iOS10.2.1

**Comment by chris-brookes** [comment]
@gregdorward - I have retested the fix and it is working fine on two iPhones (iOS 8 and 10). Can you have another go please.

**Comment by gregdorward** [comment]
Yeah, @chris-brookes it looks to be working for me now too - weird. I'll close it, seeing as that was the last issue remaining
