### ISSUE TITLE
Team profile pages - Links to profile pages of people not with us any more will show a 404 page.

### ISSUE THREAD

**Issue by chris-brookes** [redbadger/website-honestly#391]
**Description of the issue:**
On case study pages we show people that were in the team and they have links to their profile page. Some people on those teams are not with us any more and will not have a profile page to link to when the new profile pages are released, therefore a 404 error page will be shown.

**Steps to reproduce:**

1. Go to a case study page eg. https://www-staging.red-badger.com/our-work/case-study/sky-cms/
2. Click on a profile of someone who is not with us any more eg. Jon Sharratt

**Actual result:**
The site will show a 404 error page.

**Expected result:**
The site should redirect to the profile list page. (https://red-badger.com/about-us/people/)

People that need the redirect:
_**TO BE UPDATED**_

**Comment by markholland** [comment]
This bug doesn't apply anymore as the current design doesn't include people in the case studies.
