### ISSUE TITLE
Fav images missing on case study pages.

### ISSUE THREAD

**Issue by chris-brookes** [redbadger/website-honestly#392]
**Description of the issue:**
With the new Our Work page some of the images have been moved to a different address/folder. The old case study details pages are calling for the fav images on the old address, and so are getting a 404 response.

**Steps to reproduce:**

1. Open any case study details page eg. https://www-staging.red-badger.com/our-work/case-study/camden-market/
2. View the fav icon and the page title in the browser tab.

**Actual result:**
The icon is missing. All of these icons will be missing:
	https://www-staging.red-badger.com/apple-touch-icon-57x57.png
	  \_____ error code: 404 (not found)
	https://www-staging.red-badger.com/apple-touch-icon-60x60.png
	  \_____ error code: 404 (not found)
	https://www-staging.red-badger.com/apple-touch-icon-72x72.png
	  \_____ error code: 404 (not found)
	https://www-staging.red-badger.com/apple-touch-icon-76x76.png
	  \_____ error code: 404 (not found)
	https://www-staging.red-badger.com/apple-touch-icon-114x114.png
	  \_____ error code: 404 (not found)
	https://www-staging.red-badger.com/apple-touch-icon-120x120.png
	  \_____ error code: 404 (not found)
	https://www-staging.red-badger.com/apple-touch-icon-144x144.png
	  \_____ error code: 404 (not found)
	https://www-staging.red-badger.com/apple-touch-icon-152x152.png
	  \_____ error code: 404 (not found)
	https://www-staging.red-badger.com/apple-touch-icon-180x180.png
	  \_____ error code: 404 (not found)
	https://www-staging.red-badger.com/favicon-32x32.png
	  \_____ error code: 404 (not found)
	https://www-staging.red-badger.com/favicon-194x194.png
	  \_____ error code: 404 (not found)
	https://www-staging.red-badger.com/favicon-96x96.png
	  \_____ error code: 404 (not found)
	https://www-staging.red-badger.com/android-chrome-192x192.png
	  \_____ error code: 404 (not found)
	https://www-staging.red-badger.com/favicon-16x16.png
	  \_____ error code: 404 (not found)

![screen shot 2017-03-03 at 15 33 20](https://cloud.githubusercontent.com/assets/9529865/23557760/027a83fc-0029-11e7-8a6e-b79efb22d45d.png)

**Expected result:**
This icon should be shown ![apple-touch-icon-57x57](https://cloud.githubusercontent.com/assets/9529865/23557669/ac7354ac-0028-11e7-9c77-ee9e9ebae828.png)

The icon images are now saved in folder /assets-honestly/favicons/
eg. https://www-staging.red-badger.com/assets-honestly/favicons/favicon-16x16.png

**Comment by dpiatek** [comment]
This seems to be fixed
