### ISSUE TITLE
Incorrect link address on Digital Designer job vacancy page.

### ISSUE THREAD

**Issue by chris-brookes** [redbadger/website-honestly#393]
**Description of the issue:**
A link in the current vacancies Digital Designer details page is incorrect. The link 'Agile Survival Guide Designers' is using the wrong address. 

**Steps to reproduce:**

1. Go to the Digital Designer job vacancy page https://red-badger.com/about-us/join-us/digital-designer
2. Click on the 'Agile Survival Guide Designers' link.

![screen shot 2017-03-03 at 13 47 49](https://cloud.githubusercontent.com/assets/9529865/23558806/d2b15354-002c-11e7-98ed-2b3d736122a7.png)

**Actual result:**
Link goes to wrong address:
https://red-badger.com/blog/2013/02/14/agile-survival-guide-for-designers/

**Expected result:**
Link should go to this address:
https://red-badger.com/blog/agile-survival-guide-for-designers

**Comment by gregdorward** [comment]
@chris-brookes I think this one has been fixed, would you be able to take a quick look to confirm please?

**Comment by chris-brookes** [comment]
Yep this has been fixed.
