### ISSUE TITLE
Change design of blog category buttons to match the People page.

### ISSUE THREAD

**Issue by chris-brookes** [redbadger/website-honestly#396]
**Description of the issue:**
The design of the category buttons at the top of the blog site (https://red-badger.com/blog/) need to change to match the design of the category buttons on the Red Badger People page. (https://red-badger.com/about-us/people)

**# Buttons to change on the Blog site:**
![screen shot 2017-03-06 at 10 38 08](https://cloud.githubusercontent.com/assets/9529865/23606737/f6ac15ee-0259-11e7-88c0-0f706cd18c9e.png)

**# Correct design:**
![screen shot 2017-03-06 at 10 38 29](https://cloud.githubusercontent.com/assets/9529865/23606755/08b9f940-025a-11e7-863d-825a9e6ab475.png)

**Comment by mveritym** [comment]
Fix is here: https://github.com/redbadger/blog-squarespace-template/pull/60

**Comment by chris-brookes** [comment]
Deployed to live.
