### ISSUE TITLE
The service worker isn’t caching pages

### ISSUE THREAD

**Issue by grahammendick** [redbadger/website-honestly#400]
The service worker isn’t caching pages

**Steps to reproduce:**
You should run this test against a staging **deployment branch** and **not** against development, live or staging. That’s because you must ensure that you haven’t visited the Urls before. The staging deployment Urls contain a shah which guarantee their uniqueness. If you used Urls that you’ve previously visited then there’s no telling what’s already cached by your browser and service worker.

1. Choose any website honestly PR and click a 'View deployment' button (each time you run the test, choose a different 'View deployment' button or PR)
2. Click the 'About Us' menu link
3. Turn off WI-FI (turn it off on your Mac, **not** from dev tools)
4. Refresh the page (Command + R)

**Actual result:**
You see 'The site can’t be reached' page. 

**Expected result:**
You see the 'About Us' page

If you don’t press refresh at step 4 then it looks like the service worker is working because you can navigate around the site even though you’re offline. But really the service worker isn’t playing any part in this. The reason you can navigate around even though you’re offline is because website-honestly is a SPA and so all navigation happens client side. You’d get the exact same behaviour if we removed the service worker.

The only thing the service worker is caching is the css, js and png files. It doesn’t cache any pages and so it can’t return the 'About Us' page when you press refresh. It used to cache pages but [we removed this functionality](https://github.com/redbadger/website-honestly/commit/725d47fad1c67c6042a5ba5db7f9b7e0ac061962) when [dynamic routes broke the page caching](https://github.com/redbadger/website-honestly/issues/231).

**Suggested fix:**
_You can see an implementation of the following fix in the [service worker branch](https://github.com/redbadger/website-honestly/compare/service-worker)._

We don’t need to cache all the pages to fix the service worker (which is what caused [the problem before](https://github.com/redbadger/website-honestly/issues/231)). Instead we just have to cache the home page response. Then, whenever we get a request for a page, we return the cached home page response. The client side navigation router will kick in and navigate you to the page that matches your Url (similar to how navigation works in 'make dev' mode).

We can tell if the request is for a page by checking that there’s no file extension on the Url. We need to treat blog requests differently because they come from squarespace and can’t be rendered on the client. So, if the Url starts with 'blog’, we’ll return the ['Offline' page](https://red-badger.com/offline/). That means we need to add the 'Offline' page to the cache on install of the service worker.

We should also enhance the asset cache to include fonts and jpegs (woff2 and jpg). That way the page will look exactly the same after pressing refresh when offline.

We’ll follow the [guidance on how to update a service worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#Updating%20your%20service%20worker). So we’ll use a 'v2' cache and delete the 'v1' on activation of the new service worker.

**Comment by JoeStanton** [comment]
I think it would be very worthwhile to investigate how we can actually unit test the ServiceWorker. It seems to fail quite a lot, so I guess it would be a combination of testing the pure logic in a unit test and perhaps running a headless Chrome browser test to make sure it does the right thing? With headless chrome you can assert that certain pages come from cache etc.

**Comment by grahammendick** [comment]
I think it’s a process problem. Service Worker was never a story/ticket so testers weren’t aware of it. If it was a story then the [PR that broke the service worker](https://github.com/redbadger/website-honestly/pull/250) wouldn’t have got through testing.

**Comment by asavin** [comment]
It was a story on a board, but we have underestimated the impact of it on the site. Part of the problem was that the site still consisted of 3 separate apps and we only wanted to cache Honestly part.

But I think both of you are right - if we still want to keep support for SW:s we should look into automated testing, and improve on the manual testing front.
