### ISSUE TITLE
Typography on old website is not loading Sentinel

### ISSUE THREAD

**Issue by Monikamu** [redbadger/website-honestly#401]
**Description of the issue:**
Sentinel is not loading on old website, check all case studied and the tech page.

**Browser used:**
Chrome 56.0.2924.87
**OS used:**
MacOS Sierra
**Device used:**
Mac Laptop

**Steps to reproduce:**

1. https://red-badger.com/services/technology/
2. https://red-badger.com/our-work/case-study/fortnum-and-mason/
3. all case studies
...etc

**Actual result:**
<img width="1123" alt="screen shot 2017-03-07 at 16 58 00" src="https://cloud.githubusercontent.com/assets/16961478/23668050/bdb56dd6-0357-11e7-9e50-b325648d35ef.png">

**Expected result:**
It should use Sentinel Black.

**Comment by asavin** [comment]
Fixed now. The reason was that I made a new font set on typography.com, migrated Website Honestly to use it, and disabled the old font set assuming that no one use it anymore. Completely forgot about the old site!

Should be all back to normal now.
