### ISSUE TITLE
Social feed bunched up and cannot be swiped on Safari with JS disabled

### ISSUE THREAD

**Issue by gregdorward** [redbadger/website-honestly#402]
**Description of the issue:**
When a user has disabled JavaScript manually in Safari, the Social Feed on the About Us page becomes bunched up and cannot be swiped. See the attached screenshot for an illustration

**Browser used:**
Safari

**OS used:**
OSX

**Device used:**
MacBook Pro

**Steps to reproduce:**
1. Launch Safari
2. Disable JavaScript in the browser
3. Navigate to https://red-badger.com/about-us/
4. Scroll down the the Social Feed

**Actual result:**
Shown in the screenshot
<img width="1280" alt="screen shot 2017-03-08 at 16 56 34" src="https://cloud.githubusercontent.com/assets/20296527/23714402/e2f98428-0420-11e7-8e20-292bc64a6ee8.png">

**Expected result:**
This content should not be bunched up, and the user should be able to swipe through the content

**Comment by grahammendick** [comment]
@gregdorward is this on our [supported browser list/os list](https://github.com/redbadger/website-honestly/blob/master/.github/PULL_REQUEST_TEMPLATE.md)?

**Comment by gregdorward** [comment]
Only affects version 9.1 of Safari (old), so will close this based on Roisi's feedback
