### ISSUE TITLE
Welcome email Case Study dividers are misaligned within Gmail in browser 

### ISSUE THREAD

**Issue by gregdorward** [redbadger/website-honestly#405]
**Description of the issue:**
When accessing the "Let's make things better" email within a mobile browser (Safari, Chrome or Firefox), the dividing lines between the case studies are misaligned. See the below screenshot for an illustration.

<img width="384" alt="screen shot 2017-03-10 at 10 14 50" src="https://cloud.githubusercontent.com/assets/20296527/23791782/49824778-057c-11e7-9e4f-43d0a1776aa1.png">

**Browser used:**
Safari, Chrome, Firefox

**OS used:**
iOS10

**Device used:**
iPhone 6s

**Steps to reproduce:**

1. On an iPhone, in Gmail, on a browser, open the "Let's make things better" email
2. Check the dividing lines between the case studies

**Actual result:**
The dividing lines look like this:
<img width="384" alt="screen shot 2017-03-10 at 10 14 50" src="https://cloud.githubusercontent.com/assets/20296527/23791848/8ec909de-057c-11e7-9bae-3a2443415356.png">

**Expected result:**
It should look as per this screenshot, taken within the Gmail app:
<img width="378" alt="screen shot 2017-03-10 at 10 31 17" src="https://cloud.githubusercontent.com/assets/20296527/23791919/cc7494e2-057c-11e7-90d8-fa2f646de802.png">

**Comment by dpiatek** [comment]
@chris-brookes could check if this is still happening?

**Comment by chris-brookes** [comment]
@dpiatek - No it's not doing that now.... it looks even worse!
It is now showing the mobile layout, but it is not scaling it to fit on the screen. Most of the page is being cut off, and with Firefox you can't scroll across to the right to see the rest of the email, you can only scroll up & down and see the left hand side. Also the vertical lines are still being shown. In the mobile layout, only the horizontal lines that split each section should be shown.

![screenshot_20180309-163621](https://user-images.githubusercontent.com/9529865/37219652-06ae688c-23bc-11e8-9659-9370544bebf0.png)


But now it is also not showing correctly in the gmail app. There should only be one vertical line between each section of the table.

![screenshot_20180309-170127](https://user-images.githubusercontent.com/9529865/37219672-1181e41e-23bc-11e8-99f1-49fb3c8264e8.png)
