### ISSUE TITLE
Team profile pages - peoples name and images do not match up when changing filtering on slow internet connections

### ISSUE THREAD

**Issue by sebflipper** [redbadger/website-honestly#408]
**Description of the issue:**

On slow internet connections, when changing the filter, peoples name and images do not match up.

**Browser used:** Google Chrome 57
**OS used:** Mac OS

**Steps to reproduce:**

1. Navigate to: https://red-badger.com/about-us/people/
2. Open the Devtools > Network > Disable cache and Set Throttling to 2G or 3G
3. Change the people category filter to a different category

**Actual result:**

Peoples names no longer match the images displayed 😅

**Expected result:**

Peoples names should match the images displayed

**Comment by chris-brookes** [comment]
Issue fixed and live.
