### ISSUE TITLE
Blog pages cannot be parsed by Pocket

### ISSUE THREAD

**Issue by sheepsteak** [redbadger/website-honestly#411]
**Browser used: Any**
**OS used: Any**
**Device used: Any**

**Steps to reproduce:**

1. go to [Pocket](getpocket.com)
2. make an account or log in with an existing one
3. add a blog post from red-badger.com/blog
4. try to access the article in the reading list

**Actual result:**
You're redirected to the URL of the article on red-badger.com instead of seeing the reading view.

**Expected result:**
Pocket opens up a reading view with a parsed version of the page.

If you use the Pocket app it's even easier to see what's wrong as it will say that it can't show the article view as it can't parse the page properly. It's annoying as pages can't be saved to read later.

I think the reason it struggles it because there is no `<article>` element on the site surrounding the content. I also noticed that the blog title is a `h2` when it should be a`h1` (in fact there are no `h1` elements on the page at all).

**Comment by dpiatek** [comment]
This is fixed
