### ISSUE TITLE
Lead Forensics Incorrectly Configured

### ISSUE THREAD

**Issue by grahammendick** [redbadger/website-honestly#413]
**Description of the issue:**
The Lead Forensics code is incorrectly added to the `head` section. It contains a `noscript` tag with an image and images aren't allowed in the `head` section.

**Browser used:** Google Chrome
**OS used:** N/A
**Device used:** N/A

**Steps to reproduce:**
1. Disable JavaScript 
2. Go to red-badger.com

**Actual result:**
Open dev tools and see that the `noscript` tag in the head section is empty and the image is moved into the `body` section

**Expected result:**
The `noscript` tag should be in the `body` section

**Comment by dpiatek** [comment]
Closing this as  Lead Forensics will be removed in the near future
