### ISSUE TITLE
Prismic People Page changes not being reflected after a badgerbot update

### ISSUE THREAD

**Issue by gregdorward** [redbadger/website-honestly#421]
**Description of the issue:**
When a change is made to an individual's bio in Prismic, i.e. to publish/unpublish, a badgerbot honestly update command does not pull through the change. I have found that in order for the change to be made, you need to wait ~5 minutes before using this command. On a few occasions, I've had to run this command a few times to see a change on the site.

**Browser used:**
Firefox, Safari, Chrome

**OS used:**
OS Sierra

**Device used:**
MacBook Pro

**Steps to reproduce:**

1. In Prismic, make a change to a Badger Bio, i.e. edit, publish or unpublish it
2. Following the change, type to "badgerbot honestly update" command into Slack
3. Clear your browser cache and view the People page

**Actual result:**
The update is not reflected on the RB site

**Expected result:**
The change should be deployed as soon as the "badgerbot honestly update" command is typed into Slack. You should not have to wait for around 5 minutes before triggering this

**Comment by asavin** [comment]
Oh wow. We should probably report this to Prismic support - basically a delay between edit of the document and content fetched via an API.

**Comment by Roisi** [comment]
@asavin can you give them a bell? If it's not an us thing we can consider contact with them solving this :)

**Comment by asavin** [comment]
Just chatted to @gregdorward - seems like an issue that only appeared today. Will contact the Prismic support if this persists.

**Comment by gregdorward** [comment]
It may be the case that the "badgerbot honestly staging update" is not functioning. Taking that out of the equation, I can still see examples where the UI of the site is not updating following on from a change, but when I make a direct request to Badger Brain, the correct information is returned. This seems pretty sporadic, and cannot be reproduced every time.

The latest instance was after publishing a badger profile. Badger Brain returns the individual (id "WH31dyUAAGdxJJtb"), but they are not being displayed on the front-end, despite clearing my cache

**Comment by gregdorward** [comment]
No reoccurrence of this in months, so I'm closing this ticket
