### ISSUE TITLE
Typofix: "About Us" in navigation should be "About us"

### ISSUE THREAD

**Issue by sarigriffiths** [redbadger/website-honestly#423]
**Description of the issue:**
Type in header navigation.

**Actual result:**
<img width="339" alt="screenshot 2017-03-27 14 32 28" src="https://cloud.githubusercontent.com/assets/3176873/24358878/795b7042-12fa-11e7-86cf-61679c419c8f.png">

**Expected result:**
<img width="319" alt="screenshot 2017-03-27 14 34 44" src="https://cloud.githubusercontent.com/assets/3176873/24358902/8ac96fc8-12fa-11e7-83e0-e1302be9b709.png">

**Comment by gregdorward** [comment]
This was fixed in #445 - closing
