### ISSUE TITLE
Mailchimp - links in footer don't open in a new tab when viewing Badger News email in a browser

### ISSUE THREAD

**Issue by gregdorward** [redbadger/website-honestly#430]
**Description of the issue:**
When viewing the Badger News email in a browser, if I click on any of the links in the footer, i.e. a social media link or preferences etc., the content loads in the same tab. This content needs to open in a new tab

**Browser used:**
Chrome, Safari, Firefox

**OS used:**
iOS
Android

**Device used:**
iPhone
Pixel
Macbook Pro

**Steps to reproduce:**

1. Open the Badger News email in a browser
2. Tap a link in the footer

**Actual result:**
The content will be loaded in the same tab

**Expected result:**
The content should be loaded in a new tab

**Comment by gregdorward** [comment]
@grahammendick already has a fix for this one from the previous welcome emails

**Comment by grahammendick** [comment]
I've copied the social links section from the welcome journey and all's good

**Comment by grahammendick** [comment]
Oops, forgot the preferences and unsubscribe links - they're done now, too

**Comment by gregdorward** [comment]
Retested this one yesterday and all links in the footer are now correctly opening content in a new tab - closing ticket
