### ISSUE TITLE
Fields missing in Badger profiles in Staging Prismic

### ISSUE THREAD

**Issue by gregdorward** [redbadger/website-honestly#432]
**Description of the issue:**
In Prismic in Staging there are a couple of fields missing in the Badger Profile page compared to Production.

The missing fields are:

- Squarespace author

- Order

- Red Badger Achievements

These are all used in Production, so we should have the same fields for Testing in Staging. It's not certain, but to me it looks like these fields were never present in Staging

**Browser used:**
All

**OS used:**
All

**Device used:**
All

**Steps to reproduce:**

1. Open the Badger Profile Prismic page in Staging
2. Open the Badger Profile Prismic page in Production
3. Compare the fields in each

**Actual result:**
The above fields are missing in Staging

**Expected result:**
The templates should be the same in Production and Staging

**Comment by chris-brookes** [comment]
All fields have been copied from production to stage within another project, so it has fixed this issue.
