### ISSUE TITLE
Squarespace outage brings down website-honestly

### ISSUE THREAD

**Issue by grahammendick** [redbadger/website-honestly#434]
Squarespace went down yesterday (12/4). The blog part of our site stopped working, as expected. But what wasn’t expected was that website-honestly also went down.

After explaining why Squarespace brought down website-honestly, I’ll suggest what we should do about it to stop it happening again.

## Problem
We use Typography.com for our web fonts. On website-honestly we have a stylesheet link to Typography. Typography decides what font to load based on the browser. It then redirects to the relevant font stylesheet held on our Squarespace server.   

Typography and Squarespace are both involved in serving up our web fonts. If either of them fails then the web fonts won’t be returned. If they fail fast then this isn’t a problem for website-honestly. Website-honestly will work just fine with the default fonts that are built into the browser.

The problem only happens if they fail slowly. This is what happened yesterday. It took Squarespace over 7 seconds to return a failure message. Failing slowly brings down website-honestly because stylesheets are blocking requests. The browser waits until the stylesheet returns before showing any content. If Squarespace takes over 7 seconds to return the font stylesheet then the user won’t see any content at all for that time.

## Solution
The solutions isn’t to move the fonts from Squarespace to website-honestly. This wouldn’t solve the problem. If Typography takes 7 seconds to fail then we’d have the same problem as yesterday.

The solution is to make the stylesheet request from website-honestly non-blocking. That way it won’t matter how long Typography or Squarespace take to respond. Website-honestly will load up straight away with the default fonts and then, when the font stylesheet returns, it will start using the Typography fonts.

I’ve tested out this approach. I throttled the Typography request for 5 seconds and website-honestly showed a blank page for that time. Then I changed the stylesheet link to be non-blocking and website-honestly showed all the content instantly with the default fonts and, after 5 seconds, the fonts updated.

[Filament Group’s solution](https://github.com/filamentgroup/loadCSS) is the recommended approach for asynchronously css loading

**Comment by gregdorward** [comment]
So, if I'm understanding this correctly, on the odd occasion where typography takes the longest to load when hitting our site, the fonts will update after the user's on the page? It's definitely preferable to having an unnecessary dependency on typography, but I'm wondering if that would look a bit strange if it's noticeable.

Is there a 3rd option where we could possibly style to blog extract on the Homepage outside of typography, removing the call entirely from this page?

**Comment by grahammendick** [comment]
We're not removing the dependency on Typography. We get our fonts from Typography, which gets them from Squarespace. I'm proposing that we don't block the content until the font loads. Instead of showing a blank page, we should show the content straight away with the default fonts.

There was a confusing diagnosis at the time of the outage that I should clear up. The dependency on Squarespace isn't because we show featured blogs on the homepage. Website-honestly is a static site and doesn't scrape any content from the blogs. The dependency on Squarespace is only because we host the fonts on Squarespace.

We made the decision to host the fonts on Squarespace 5 months ago when the blog was created. I see no reason to change this decision when it doesn't address the problem. We'll always have a dependency on Typography so the only robust solution is to load the stylesheet in a non-blocking way.

With the solution proposed above you can get a flash as the new font loads and updates the content. We should talk this through with the UX team.

**Comment by grahammendick** [comment]
This statement I made about hosting the fonts on Squarespace is incorrect

> We made the decision to host the fonts on Squarespace 5 months ago when the blog was created


We have two separate projects on Typography. One for Website Honestly and one for the Blog. They both have identical fonts in them. Each project has a different fonts.css Url.

* Adding a stylesheet link to the Url from the **Website Honestly project** sends a request to Typography which redirects to the relevant css **hosted on website-honestly**. 
* Adding a stylesheet link to the Url from the **Blog project** sends a request to Typography which redirects to the relevant css **hosted on Squarespace**. 

Website honestly should use the Url from the Website Honestly Project and the Blog should use the Url from the Blog Project. That way, website-honestly isn’t dependent on Squarespace and Squarespace isn’t dependent on website-honestly.

It was working correctly until #397 went in. This PR correctly removed a font fallback that wasn't working correctly. But it incorrectly changed the Url to the one from the Blog project. We should revert [this change](https://github.com/redbadger/website-honestly/pull/397/commits/5ce2fbacdfd7df6fc91a76f750a8f7e702b2bc9b).

I’ll raise a separate ticket for removing the dependency on Typography by not blocking the content until the font loads.

**Comment by gregdorward** [comment]
Re-opening this issue, as only the render blocking CSS issue was fixed. To fix this one, we need to follow @grahammendick's advice in his last comment

**Comment by chris-brookes** [comment]
Update to do:
Change the fonts.css address in /website-honestly/site/index.ejs 
From - https://cloud.typography.com/7838134/7069172/css/fonts.css
To - https://cloud.typography.com/7838134/6842972/css/fonts.css

(Make sure you change the <noscript> line too.)

**Comment by chris-brookes** [comment]
This has been fixed with https://github.com/redbadger/website-honestly/pull/492
