### ISSUE TITLE
Duplicate Event Names Show Duplicate Event Details

### ISSUE THREAD

**Issue by grahammendick** [redbadger/website-honestly#436]
**Description of the issue:**
Create two events with the same name but different details. In website-honestly the two events are both listed but they both point at the same details when you select them.

**Browser used:** N/A
**OS used:** N/A
**Device used:** N/A

**Steps to reproduce:**

1. Create two events with the same name but different details
2. Select the two events from the events listing page of website-honestly

**Actual result:**
Event details displayed relating to the selected event

**Expected result:**
The same event details displayed for both events

**Comment by gregdorward** [comment]
Current example in production is the two instances of the slug 'july-react-meetup'

**Comment by markholland** [comment]
From a first look it appears Prismic is not reflecting the different uid in the slug
