### ISSUE TITLE
Can't Display More Than 100 Events

### ISSUE THREAD

**Issue by grahammendick** [redbadger/website-honestly#437]
**Description of the issue:**
If you create over 100 Events in Prismic only 100 are shown in the UI.

**Browser used:**
**OS used:**
**Device used:**

**Steps to reproduce:**

1. Create more than 100 Events in Prismic
2. Go to the Events listing page of website-honestly

**Actual result:**
Only 100 Events are displayed

**Expected result:**
All Events are displayed

**UPDATE**

The resolution to this ticket is not to increase the maximum number of events, but to either return them in chronological order, or to sort them when they're retrieved through Prismic so that the oldest events are not displayed if >100 are returned

**Comment by andyc84** [comment]
Discussed this with @AmyBadger - concluded that displaying 100 events max is acceptable, and they should be displayed chronologically (with the oldest events falling off the list).

**Comment by gregdorward** [comment]
Closing this one as not an issue - see above

**Comment by grahammendick** [comment]
@gregdorward currently the events aren't sorted so which ones drop off the end are random. We need to sort the events so the oldest ones drop off the end

**Comment by davidbasalla** [comment]
@markholland This might be related to https://github.com/redbadger/website-honestly/issues/435?
