### ISSUE TITLE
Typography is Blocking

### ISSUE THREAD

**Issue by grahammendick** [redbadger/website-honestly#438]
**Description of the issue:**
See #434 for background. We display web fonts by making a stylesheet request to Typography (which then redirects to the relevant css file on our servers). Be default, stylesheet requests are blocking. The user won’t see any content until the Typography request returns.

**Browser used:** N/A
**OS used:** N/A
**Device used:** N/A

**Steps to reproduce:**
I don't know of an easy way to slow down just the Typography request. Instead I wrote my own test-server to play the role of Typography.com:

1. Create a node express app that redirects to the css file after 5 seconds 
```
var express = require('express')
var app = express()

app.get('/', function (req, res) {
  setTimeout(() => {
    res.redirect('https://red-badger.com/assets-honestly/551381/19AE4B7538BC1E1C8.css');
  }, 5000)
})

app.listen(3000, function () {
  console.log('Example app listening on port 3000!')
})
```
2. Start the node express app
3. In index.ejs of website-honestly, replace the url in the stylesheet link from `https://cloud.typography.com...` to `http://localhost:3000/` (the node express server)
4. Start website-honestly

**Actual result:**
The content isn't displayed until after 5 seconds

**Expected result:**
The content is displayed straight away

**Comment by grahammendick** [comment]
I think we should follow [Filament Group’s solution](https://github.com/filamentgroup/loadCSS) to asynchronously load css. The content is displayed straight away using the fallback default font specified. When the new font downloads the display starts using it. This changing of default to new font causes a slight flash. Need to check that the UX team are happy with this.

**Comment by gregdorward** [comment]
@sarigriffiths, I think this would be a good one to get near to the top of our backlog, as it should have a good impact on page load performance. It will need UX sign off once it's been put in place, as it's possible the user will see a flash of unstyled text on first load. Ultimately, it's going to be a case of weighing up whether the quicker load time is worth this risk
