### ISSUE TITLE
Edge 14: Webfonts are broken

### ISSUE THREAD

**Issue by asavin** [redbadger/website-honestly#44]
<img width="397" alt="dashboard" src="https://cloud.githubusercontent.com/assets/487468/19158251/f3425f4e-8bdf-11e6-8311-d7f60f14b227.png">

For whatever reason webfonts appear to be broken on IE Edge 14 (tested on Win10). Works fine on Edge 13 and IE 11.

**Comment by lpil** [comment]
Works in Edge 14 on VMs and on Andrei's windows laptop, so seems it's a browserstack issue.
