### ISSUE TITLE
Duplicate images on Event page

### ISSUE THREAD

**Issue by gregdorward** [redbadger/website-honestly#450]
**Description of the issue:**
The following event has duplicate images, one from Prismic, and one hardcoded:

https://red-badger.com/about-us/events/2015/05/21/digital-shoreditch-web-accessibility---are-you-excluding-a-fifth-of-the-uk-population

Prismic image - https://prismic-io.s3.amazonaws.com/rb-website/eeae2d53e9a967c4ca2c4b8a0ed90bc3aa0d62f0_accessibility-workshop.png

Hardcoded image - /images/content/events/accessibility-workshop.png

This second image needs to be removed

**Browser used:**
All

**OS used:**
All

**Device used:**
All

**Steps to reproduce:**

1. Load https://red-badger.com/about-us/events/2015/05/21/digital-shoreditch-web-accessibility---are-you-excluding-a-fifth-of-the-uk-population
2. Check the images on the page

**Actual result:**
There are duplicate images of differing sizes

**Expected result:**
There should only be one image, served from Prismic

<img width="937" alt="screen shot 2017-05-04 at 13 48 08" src="https://cloud.githubusercontent.com/assets/20296527/25704184/56f3510c-30d0-11e7-8cfd-fadad709f44e.png">

**Comment by markholland** [comment]
I'm unable to reproduce this as the event in question is no longer listed in the live site. I can access it in [staging](https://www-staging.red-badger.com/events/2015/05/21/digital-shoreditch-web-accessibility---are-you-excluding-a-fifth-of-the-uk-population/) but am unable to observe the issue stated.
