### ISSUE TITLE
Sally favicon appears blurry on Blog page

### ISSUE THREAD

**Issue by gregdorward** [redbadger/website-honestly#452]
**Description of the issue:**
When on the Blog page, the favicon of Sally the Badger at the top of the page looks blurry.

<img width="224" alt="screen shot 2017-05-04 at 15 41 53" src="https://cloud.githubusercontent.com/assets/20296527/25709124/5b6efa46-30e0-11e7-99c6-86ea5b0f286a.png">

This has been seen by myself (Greg) on Firefox and Nathalie on Chrome

**Browser used:**
Chrome and Firefox

**OS used:**
Mac OS Sierra

**Device used:**
MacBook Pro

**Steps to reproduce:**

1. Navigate to a Website Honestly page
2. Check the favicon on the tab
3. Navigate to the Blog page
4. Check the favicon again

**Actual result:**
The favicon appears blurry

**Expected result:**
The favicon should have the same resolution as the other Website Honestly pages

**Comment by dpiatek** [comment]
Can't replicate
