### ISSUE TITLE
Pages archived in Prismic are still accessible on the live site.

### ISSUE THREAD

**Issue by chris-brookes** [redbadger/website-honestly#457]
**Description of the issue:**
Some profile pages have been archived within Prismic, but they are still accessible on the live site if you know the direct address.
These profiles are archived. They are not showing on the profile list page, but you can still view the profiles if you go direct to their profile details page.

![screen shot 2017-05-11 at 14 17 24](https://cloud.githubusercontent.com/assets/9529865/25953508/80327daa-365b-11e7-96a0-137f38a801c5.png)

**Steps to reproduce:**

1. Go to any of these profile detail pages:
https://red-badger.com/about-us/people/roisi-proven/
https://red-badger.com/about-us/people/melissa-marshall/
https://red-badger.com/about-us/people/anna-doubkova/

**Actual result:**
You are able to view these pages.
 
**Expected result:**
These badger profiles are archived in Prismic, so the pages should not appear on the live site.

**Comment by Xanndarr** [comment]
Badgerbot is compiling the honestly site (using the list of badgers returned from Prismic via badgerbrain) and then pushing it to S3. In about-us/badgers/ are a list of profile pages for all badgers. The compilation process generates a new folder for any badgers that don't have one. It doesn't remove folders of archived badgers. This is to avoid downtime while deploying:

[This](http://brain-staging.red-badger.com/graphql?query=%7BallBadgers%7B%0A%20%20firstName%0A%20%20lastName%0A%7D%7D) graphQL query seems to return all badgers from Prismic. This is up to date and archived badgers aren't surfaced in this request.

Should look into a solution that removes any badger profiles that don't match a name from graphql. Seems like a reasonable solution to avoid down time when deploying

**Comment by Xanndarr** [comment]
If the lambda uses aws-cli to push the build to s3, an `aws s3 sync` on the folder might be sufficient

**Comment by chris-brookes** [comment]
Fixed with #524
