### ISSUE TITLE
Second meet up page opened after using mail chimp

### ISSUE THREAD

**Issue by AndreiDanielIonescu** [redbadger/website-honestly#47]
When the user:
- goes to the meet up page.
- enters an email adress in the get updates field
- is redirected to the mail chimp app
- chooses to turn back to the main page

 The user will have a new page opened (in the mail chimp page) instead to be returned to the original page. He will end having to identical pages opened

**Comment by zoeabryant** [comment]
Wrong repo! This should be added here- https://github.com/redbadger/react.london/issues

**Comment by zoeabryant** [comment]
now in- https://github.com/redbadger/react.london/issues/259
