### ISSUE TITLE
Style change on footer menu

### ISSUE THREAD

**Issue by chris-brookes** [redbadger/website-honestly#479]
**Description of the issue:**
The footer menu and mobile header menu should only show the red underline when you hover over each of the menu options.

This also needs to be added to the email and phone number on the footer.

A spacing of about 20px needs to be added between the email and phone number.

![screen shot 2017-06-02 at 16 40 29](https://cloud.githubusercontent.com/assets/9529865/26733465/d212c4fa-47b2-11e7-9b76-005137747e51.png)

![screen shot 2017-06-02 at 16 42 46](https://cloud.githubusercontent.com/assets/9529865/26733474/d695fe84-47b2-11e7-931c-51aed5adcf7a.png)

**Comment by Xanndarr** [comment]
This needs to be mirrored on the blog template as well
