### ISSUE TITLE
Mailchimp accessibility findings

### ISSUE THREAD

**Issue by gregdorward** [redbadger/website-honestly#494]
**Description of the issue:**

## Sign up email

- [x] 'Read our tech blogs' button needs to have 'font-weight: bold' to pass contrasting guidelines

- [x] HTML needs a lang attribute

- [ ] Remove restriction on zooming and scaling

## We solve complex problems...

- [x] 'See our work' button needs to have 'font-weight: bold'

- [x] HTML needs a lang attribute

- [ ] Links need to be discernible, i.e. Fortnum and Mason and other case studies are links, which is not obvious

- [ ] Remove restriction on zooming and scaling

## We love tech...

- [x] 'What we do' button needs to have 'font-weight: bold'

- [x] HTML needs a lang attribute

- [ ] Remove restriction on zooming and scaling

## Badger News

- [x] '#BadgerNews' text needs to be increased to size 20 font

- [x] HTML needs a lang attribute

- [ ] Remove restriction on zooming and scaling

**Comment by cwilgenhoff** [comment]
@gregdorward Most of the requested changes have been addressed with the exception of the zoom restriction, due I'm not sure how this was achieved. Do you know who knows about it?

**Comment by gregdorward** [comment]
I believe that we've taken this as far as we can right now. We'll continue to accessibility test any new campaign emails. A lot of the open source tools report false negatives, where issues don't really exist. Closing
