### ISSUE TITLE
Technology Page - multiple layout issues

### ISSUE THREAD

**Issue by chris-brookes** [redbadger/website-honestly#496]
**Description of the issue:**
The newsletter sign-up section has multiple layout issues.

**When viewed with JS:**
1. More padding needed below the text on step 3 when in mobile view. Change to 30px bottom padding.
<img width="343" alt="screen shot 2017-06-23 at 15 40 24" src="https://user-images.githubusercontent.com/9529865/27690111-4b28c6ac-5cd8-11e7-9e26-500b53333a91.png">

 2. (From #493 Priority 3) Add 10px of padding to the top of the 'style__subTitle___1k1J- _fonts__fontXS___2mdTk _fonts__sansSerif___3iE3M' element
 
**When viewed in NON-JS:**
1. The email input box and the original Sign Up button should not be shown. 
2. Remove the set width on the text above the button.
3. Change the colour of the button to match the colour and hover-over colour of the normal Sign Up button. (#212121, hover over #606060)
4. Increase the button size so all text fits on when viewing in mobile size. (min 320px wide)

![screen shot 2017-06-29 at 12 47 39](https://user-images.githubusercontent.com/9529865/27691298-8223e116-5cdb-11e7-8b0f-219c9affc794.png)

![screen shot 2017-06-29 at 14 52 23](https://user-images.githubusercontent.com/9529865/27691304-85a105b2-5cdb-11e7-8b18-2e25649fc948.png)

**Comment by gregdorward** [comment]
Done
