### ISSUE TITLE
Privacy policy not linked to in footer

### ISSUE THREAD

**Issue by gregdorward** [redbadger/website-honestly#505]
**Description of the issue:**
In the footer, we display the text "We use cookies on our website. For more information, view our privacy policy."

Currently, we are not linking to any document though (so far I'm unsure if one exists to link to)

**Steps to reproduce:**

1. On Website Honestly, scroll down to the footer

**Actual result:**
A privacy policy is mentioned in the footer, but not linked to

**Expected result:**
We should be linking to a privacy policy if we mention one

**Comment by dpiatek** [comment]
This is a story already
