### ISSUE TITLE
Auto check system to test cloud.typography.com

### ISSUE THREAD

**Issue by gregdorward** [redbadger/website-honestly#541]
Background - Typography has proven to be flaky in the past, sometimes going offline, meaning that fallback fonts are used on our site. The typography call no longer blocks the rendering of the site, so this is less of a severe issue than it used to be.

The best outcome for this one would be an automated way of checking the uptime and downtime of Typography, to give us some tangible metrics to provide to them

**Comment by dpiatek** [comment]
We did not experience this behaviour in a long time - can reopen if it starts happening again.
