### ISSUE TITLE
Epic - Improve the 'Contact us' form

### ISSUE THREAD

**Issue by gregdorward** [redbadger/website-honestly#545]
To be broken down into smaller stories

Background - This was one of the outcomes of a workshop, held to come up with new ways to attract a potential client, specifically a CMO

**Comment by gregdorward** [comment]
Needs a UX resource to understand the issue (if one exists), and come up with potential solutions.

Note - We did notice that we had in fact received a number of queries through this form, so it may be that this is performing better than originally thought.

**Comment by dpiatek** [comment]
This was done
