### ISSUE TITLE
Epic - Improve the navigation of Website Honestly and the Blog

### ISSUE THREAD

**Issue by gregdorward** [redbadger/website-honestly#546]
To be broken down into smaller stories

Background - This was one of the outcomes of a workshop, held to come up with new ways to attract a potential client, specifically a CMO. It was decided as a group that it's sometimes difficult to find the content you are looking for on our site, and isn't particularly user-friendly for a first time user.

**Comment by gregdorward** [comment]
Needs a UX resource to investigate possible solutions

**Comment by dpiatek** [comment]
Confirmed with @sarigriffiths that this was done
