### ISSUE TITLE
Graphical issues with IE11

### ISSUE THREAD

**Issue by AndreiDanielIonescu** [redbadger/website-honestly#55]
There are several issues related to the Internet Explorer 11 browser:
 - the padlock test is overlapping over the lines (it's a single line and not warped) 
 - the separation between the black and white areas has a thin line out of place
 - the image ,,vision,validation,delivery,solution'' is smaller than on other browsers
 - the whole footer has graphical issues (map crossing over the area, links and icons)
 
Please note that test was performed on IE11 on a virtual machine with win7.

![p_20161011_113056](https://cloud.githubusercontent.com/assets/22678752/19267987/b2d97988-8fa9-11e6-959d-e870bec41eb9.jpg)
![p_20161011_113104](https://cloud.githubusercontent.com/assets/22678752/19267989/b2dd5850-8fa9-11e6-8d93-4bb010bd51de.jpg)
![p_20161011_113123](https://cloud.githubusercontent.com/assets/22678752/19267986/b2d8cba0-8fa9-11e6-8e9a-f76faca9f889.jpg)
![p_20161011_113220](https://cloud.githubusercontent.com/assets/22678752/19267988/b2dd0616-8fa9-11e6-9067-575c844f5187.jpg)

**Comment by asavin** [comment]
Should this be broken down into multiple issues?

**Comment by lithin** [comment]
I don't think that's necessary. We fixed first two with @AndrewBestbier. The "brie problem" isn't unfortunately fixable without using all sorts of crazy hacks and as it's only a small issue, we'd suggest not to waste our time on it. We're fixing footer & case study slice now :)
