### ISSUE TITLE
Fortnum and Mason tea case study

### ISSUE THREAD

**Issue by gregdorward** [redbadger/website-honestly#564]

**Comment by gregdorward** [comment]
Linked to #444 

Blocked until #557 is approved by F&M

**Comment by davidbasalla** [comment]
Closing this as the case study has gone live [1] and we link to it from the 'our-work' page [2] as of https://github.com/redbadger/website-honestly/pull/644

[1] https://red-badger.com/our-work/case-study/fortnum-and-mason-digital-transformation
[2] https://red-badger.com/our-work
