### ISSUE TITLE
Investigate whether A/B testing is possible on Website Honestly

### ISSUE THREAD

**Issue by gregdorward** [redbadger/website-honestly#593]

**Comment by daralthus** [comment]
I had a bit of a look into this, so brain dumping here:

A lot depends on the exact use-case of why we want to a/b test: 
Honestly probably won't need full blown feature flagging like ![LaunchDarkly](https://launchdarkly.com/) for every feature. It's most likely for bounce rate or conversion rate optimization for landing pages. 
The two most commonly used are ![Optimizely](https://optimizely.com) and ![Unbounce](https://unbounce.com/) Alternatively we can save money by relying on development time for implementing the changes and Google Analytics for tracking.

## Variations via GUI
Optimizely has a nice GUI to edit the variations on the site which works well. The only requirement is just dropping in their script tag in the <head/> after that you can make simple content and design changes:

![image](https://user-images.githubusercontent.com/57560/30493580-e5350342-9a44-11e7-9a3b-970e83d46ba9.png)

The generated css classes seem to be deterministic but I am not entirely sure. We might need to add our own ones to the elements if this proves to be a problem.

## Variations via JS
For more complicated changes (like rendering different components based on the variation or trigger different actions) we can use something like ![react-optimizely](https://www.npmjs.com/package/react-optimizely) 
In this case we will need to make sure it doesn't run in when we compile the sites. More on this later..
