### ISSUE TITLE
Preventing publishing of secret information.

### ISSUE THREAD

**Issue by zoeabryant** [redbadger/website-honestly#599]
Make sure that secret information (environment variables, api keys) cannot be pushed to github.
This looks like a good fit: https://github.com/thoughtworks/talisman

**Comment by dantrain** [comment]
I've had a look at [talisman](https://github.com/thoughtworks/talisman) and also [git-secrets](https://github.com/awslabs/git-secrets). The trouble is they both have awkward local installation steps that want to overwrite the git hooks we already have from [pre-git](https://github.com/bahmutov/pre-git). If they offered a simple scan command we could hook them up with pre-git but alas it doesn't look that easy 🙁

**Comment by dantrain** [comment]
I tried again with git-secrets and I think you can get it to scan without a git hook after having installed it with homebrew. However I got some false positives for AWS keys in the `assets/fonts/` folder. There is some base64 encoded data there which could cause a lot of false positives.

**Comment by dpiatek** [comment]
Blackbox was implemented and is working great :tada:

**Comment by markholland** [comment]
To be fair, Blackbox just gives us somewhere to store secrets outside of the projects repo. It doesn't stop people from pushing secrets which was the original intention of this issue.

**Comment by dpiatek** [comment]
You are right @markholland , though I'm not sure how much more we can do with that considering limited resources on the IP team. Will migrate this though as a task to Trello instead of just closing, thanks.

**Comment by dpiatek** [comment]
Aware of the drawbacks, we integrated git-secrets in #733 which should help to some extent with this problem
