### ISSUE TITLE
Camden Market case study header - Matter.js errors

### ISSUE THREAD

**Issue by dantrain** [redbadger/website-honestly#606]
Presumably there should be some coolness going on at the top of this page, but I am not seeing any coolness, only an error and warning in the console.

```
index-4b9aa.js:48 matter-js: Engine.create: engine.render is deprecated (see docs)
r.warn @ index-4b9aa.js:48

index-4b9aa.js:48 Uncaught TypeError: t.getPathSegAtLength is not a function
    at Object.r.pathToVertices (index-4b9aa.js:48)
    at index-4b9aa.js:31
    at Array.forEach (<anonymous>)
    at l (index-4b9aa.js:31)
    at t.value (index-4b9aa.js:31)
    at t.value (index-4b9aa.js:31)
    at e.notifyAll (index-4b9aa.js:31)
    at r.close (index-4b9aa.js:48)
    at r.closeAll (index-4b9aa.js:17)
    at r.perform (index-4b9aa.js:17)
``` 

**Browser used:** Chrome 62
**OS used:** MacOS Sierra
**Device used:** MacBook Pro 2017

**Steps to reproduce:**

1. Visit https://red-badger.com/our-work/case-study/camden-market/

**Actual result:** Nothing cool at the top.

**Expected result:** Something with physics and stuff?

**Comment by markholland** [comment]
So from Chrome 47 the SVG Api changed and the library we're using `matter-js` isn't going to support it but instead rely on a polyfill. So fix is to use https://github.com/progers/pathseg polyfill.
