### ISSUE TITLE
404 page - links not visible

### ISSUE THREAD

**Issue by serdemli** [redbadger/website-honestly#612]
**Description of the issue:**
On the 404 page, the links to the blog and about us aren't visible.
**Browser used:**
Chrome (Version 62.0.3202.94)
**OS used:**
MacOS High Sierra 10.13.1
**Device used:**
Macbook Pro

**Steps to reproduce:**
1. Go to red-badger.com/404
2. Notice that the blog and about us links are not visible. 

**Actual result:**
Colour of the links (the text) is #F8F8F8 . 
<img width="894" alt="screen shot 2017-11-14 at 11 25 06" src="https://user-images.githubusercontent.com/6124429/32777894-e7e77f6a-c92f-11e7-8140-5c4b4c729d3d.png">

When highlighted:
<img width="889" alt="screen shot 2017-11-14 at 11 25 42" src="https://user-images.githubusercontent.com/6124429/32777909-f1a6e9aa-c92f-11e7-936d-fe8a4b65a03b.png">

**Expected result:**
Same colour as the rest of the text (TBC with @sarigriffiths)

**Comment by pataruco** [comment]
I am closing the issue because it cannot be replicated
