### ISSUE TITLE
Some pages look broken on IE 10

### ISSUE THREAD

**Issue by frigus02** [redbadger/website-honestly#662]
**Description of the issue:**

On IE 10 many images are stretched and lines do not break where they should. This makes some pages look really broken.

**Browser used:** Internet Explorer 10
**OS used:** Windows 7

**Issues:**
- Top navigation out of view
- Lines breaks
- Stretched images

**Examples:**

Navigation not fully visible:
![homepage-broken-navigation](https://user-images.githubusercontent.com/3579251/34569335-5dcc9168-f160-11e7-84d9-c922ebde53b9.jpg)

Alignment of conent. Lines do not break:
![homepage-content-alignment](https://user-images.githubusercontent.com/3579251/34569397-8bf3b76a-f160-11e7-8146-088f6ffdbbb6.jpg)

Overlapping content on "Our work":
![our-work-overlapping-case-studies](https://user-images.githubusercontent.com/3579251/34569361-71eb80fa-f160-11e7-8b3e-ccbab02960c7.jpg)

**Comment by frigus02** [comment]
It looks like all of the issues caused by using CSS flexbox. We have an autoprefixer, so `display: -ms-flexbox;` is added everywhere. But IE 10 needs more than this to make it work correctly.

Most likely we need to fix all usages of flexbox one by one.

**Comment by davidbasalla** [comment]
Looks like there was an update to autoprefixer 6 days ago that _might_ help 🤞 -> https://github.com/postcss/autoprefixer/releases/tag/7.2.4

**Comment by davidbasalla** [comment]
https://github.com/redbadger/website-honestly/pull/664 fixes the IE10 issues on the homepage... I'll see if I get time to go through the rest of the site but since we have very few visits from IE10 this is not high priority
