### ISSUE TITLE
Homepage logos: Swap Lloyds Bank logo with HSBC

### ISSUE THREAD

**Issue by serdemli** [redbadger/website-honestly#689]
**Description of the issue:**
Swap HSBC for Lloyds Bank in the client logo list that currently sites on the homepage, under case stats.

**Actual result:**
The client logos we show under the case stats slice now has 
- Selfridges
- Tesco
- BBC
- Lloyds Bank
- cartrawler

**Expected result:**
Swap Lloyds Bank with HSBC, so the client logos are.. 
- Selfridges
- Tesco
- BBC
- HSBC
- cartrawler

**Comment by chris-brookes** [comment]
Done.
