### ISSUE TITLE
Technology page link broken on About Us page

### ISSUE THREAD

**Issue by dwynne** [redbadger/website-honestly#692]
**Description of the issue:**
In the FAQs on the `/about-us` page, under the _What tech can you use?_ question, the link to the `Technology page` is not being rendered.

![image](https://user-images.githubusercontent.com/188308/36835694-f67d1a82-1d2e-11e8-96b3-f17ef7a44ba5.png)

**Browser used:** Chrome 64.0.3282.167 (Official Build) (64-bit)
**OS used:** OSX 10.13.3
**Device used:** MBP

**Steps to reproduce:**

1. Browse to https://red-badger.com/about-us
2. Expand the _What technology can you use?_ question

**Actual result:**
Unable to click `Technology page` as the HTML is being rendered.

**Expected result:**
Should be able to click the link.

**Comment by chris-brookes** [comment]
Fixed. Content was editable in Prismic CMS.
