### ISSUE TITLE
Home page - Error message should not be shown after a valid news letter sign-up.

### ISSUE THREAD

**Issue by chris-brookes** [redbadger/website-honestly#693]
**Description of the issue:**
An invalid error message is being shown after registering for the Badger News email.

**Steps to reproduce:**

1. Go to the home page
2. Enter an email in the "Sign up to Badger News..." section.
3. The 'Thanks for signing up!' section is shown.
4. Enter the info about yourself that it asks for, then click on 'Update info'.

**Actual result:**
The normal signup section is shown again, but the an error message is being shown next to the email input box. 

**Expected result:**

The error message should not be shown and the text input box should not be highlighted.

![screen shot 2018-03-02 at 16 33 00](https://user-images.githubusercontent.com/9529865/36910281-2fca258c-1e38-11e8-8ccc-2b629acc5cd5.png)

**Comment by dpiatek** [comment]
Fixed in https://github.com/redbadger/website-honestly/pull/711
