### ISSUE TITLE
Blog page - The Delivery button is not staying highlighted after being selected.

### ISSUE THREAD

**Issue by chris-brookes** [redbadger/website-honestly#694]
**Description of the issue:**
The 'Delivery' category option on the blog page is not staying highlighted after being selected.

**Steps to reproduce:**

1. Go to the blog site https://red-badger.com/blog/
2. Select the 'Delivery' category.

**Actual result:**
The category filter works correctly on the blog stories, but the 'All' category button is highlighted.

**Expected result:**
The 'Delivery' button should be highlighted.

Delivery is missing from the css style list.
![screen shot 2018-03-05 at 15 47 05](https://user-images.githubusercontent.com/9529865/36984449-d4706b7c-208c-11e8-997d-a35ee7330254.png)

**Comment by dpiatek** [comment]
Fixed here https://github.com/redbadger/blog-squarespace-template/pull/94
