### ISSUE TITLE
Pressing Escape on a blog page leads to an error page

### ISSUE THREAD

**Issue by skaulana** [redbadger/website-honestly#702]
**Description of the issue:**
When pressing Escape on any blog article, an unexpected navigation happens to an error page

**Browser used:** Chrome latest
**OS used:** OS X High Sierra
**Device used:** MBP 2017

**Steps to reproduce:**
1. Navigate to any blog article, ex. https://red-badger.com/blog/2018/3/7/celebrating-our-kickass-badger-ladies
2. Press Escape

**Actual result:**
Navigated to https://red-badger.com/config/?frameUrl=/blog/2018/3/7/celebrating-our-kickass-badger-ladies which results in a not found/error page

**Expected result:**
No navigation action taken

**Comment by dpiatek** [comment]
@skaulana cheers for opening the issue! Esc is supposed to open the squarespace overlay. This is an SS feature, but it does not play nicely with our front-end routing. I've disabled the feature on squarespace as its not really clear how to handle these redirects.
