### ISSUE TITLE
Zeplin templates and brand guidelines have drifted in terms of grid spec for mobile

### ISSUE THREAD

**Issue by dpiatek** [redbadger/website-honestly#703]
**Description of the issue:**

The brand guidelines show a different grid for mobile then what is setup in Zeplin. Also, we don't really have a minimum supported breakpoint so it's confusing when deving/testing as it's what's considered minimum differs between designs.

We should reconcile these and chose the correct grid setup and minimum breakpoint.

**Comment by matt-paul** [comment]
Update:

We now have a newly defined grid system that can be used going forward, and can be viewed in Zeplin [here] (https://app.zeplin.io/project/57c8297fc3cf63795b6a4520/dashboard?seid=5aa8fd8611e38e2367460a09)

**Comment by matt-paul** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Instigate Grid System](https://trello.com/c/6w5tTa1I/156-instigate-grid-system)

**Comment by dpiatek** [comment]
about time @SiAshbery ;)
