### ISSUE TITLE
Technology slice, sub header should be smaller (16 px) on mobile

### ISSUE THREAD

**Issue by AndreiDanielIonescu** [redbadger/website-honestly#75]
Technology slice, sub header should be smaller (16 px). For now they are both the same dimension. Please note that this happens only on the mobile (android and IOS).

**Comment by AndrewBestbier** [comment]
"Here is a selection of what we've used on recent projects."

**Comment by AndrewBestbier** [comment]
Blocked as I am waiting for PR #43 to be merged

**Comment by AndreiDanielIonescu** [comment]
Closed as fixed and deployed
