### ISSUE TITLE
Phone menu should close when touching outside of the action box

### ISSUE THREAD

**Issue by AndreiDanielIonescu** [redbadger/website-honestly#77]
Phone menu should close when touching outside of the action box. At this moment it only closes if you use the special button.

**Comment by AndrewBestbier** [comment]
@asavin Is this possible to do?

**Comment by asavin** [comment]
It's possible, but is fiddly. I'd check with design first.

**Comment by lpil** [comment]
Just need to add a transparent element with an onclick handler that unticks the checkbox.
