### ISSUE TITLE
Please remove me from the CI pipeline

### ISSUE THREAD

**Issue by Etiene** [redbadger/website-honestly#811]
I'm still getting notified of Circle CI build failure and I get errors if I try to unsusbscribe within circle CI settings.

All the best! ❤️

**Comment by dpiatek** [comment]
Hey @Etiene ! I'm sorry to hear that. I've looked, but I don't see you in our org/team at all (it's linked to github). Maybe reach out to Circle if you are getting an error page (or they can point me in the right direction if it's on our side)?

**Comment by Etiene** [comment]
Ok, I'll contact their support then! :) I managed to turn off notifications, but couldn't remove myself from the org on circle, which I guess is because I'm no longer in the org in GitHub so I dont have permission (no idea why the org still shows on circle!)
