### ISSUE TITLE
Markup rendering on old blog post(s?)

### ISSUE THREAD

**Issue by skaulana** [redbadger/website-honestly#863]
Not sure if this is an issue with other posts as well, just spotted this particular one...

### Steps to Reproduce
1. Go to https://blog.red-badger.com/2017/1/31/cross-functional-teams-without-uxd
2. Have a look at the top of the page

### Expected Behaviour
No markup on the template

### Actual Behaviour
A line of markup is visible on the top (see below)

![image](https://user-images.githubusercontent.com/1870844/55327220-84616300-5481-11e9-9327-9a994ff6f8a8.png)

### OS/Browsers Affected
Browser used: Chrome latest
OS used: OS X Mojave
Device used: MBP 2017

**Comment by sgrowe** [comment]
The issue was in hubspot in [Custom/Blog/Squarespace/modules/header.html](https://app.hubspot.com/design-manager/4210858/code/6278244785). 

It seems `content.meta_description` contains HTML for some/all blog posts, breaking the page’s markup. So I've now changed this line
```
<meta name="description" content="{{ content.meta_description }}">
```
to this 
```
<meta name="description" content="{{ content.meta_description|striptags }}">
```
