### ISSUE TITLE
Case studies pages generates error when refreshed on live environment 

### ISSUE THREAD

**Issue by AndreiDanielIonescu** [redbadger/website-honestly#91]
Case studies pages generates error when refreshed on live environment.

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>404.html</Key>
<RequestId>85F37E1F8991AE28</RequestId>
<HostId>
G7J4iu4cpa5OK/TBJ3/eElIIFZrCz/4G0CPpQTQVxoUr+FgRDdNvM6y4BRgh6F8yThWK327F+x0=
</HostId>
</Error>

**Comment by lpil** [comment]
https://github.com/redbadger/website-honestly/blob/master/services/serverless.yaml#L95

The CDN is using the regular S3 endpoint as the origin. It needs to use the website S3 endpoint as the origin to resolve `/index.html` automatically.

```
s3: my-bucket.s3.amazonaws.com
s3 website: my-bucket.s3-website-eu-west-1.amazonaws.com
```

**Comment by Roisi** [comment]
this one is ok now, closing
