### ISSUE TITLE
Homepage - Button links

### ISSUE THREAD

**Issue by Roisi** [redbadger/website-honestly#92]
<img width="1429" alt="screen shot 2016-10-19 at 10 16 37" src="https://cloud.githubusercontent.com/assets/8049847/19512721/31ddd2ec-95e5-11e6-9d7d-e61065be7da2.png">

- Red Badger logo - http://honestly.red-badger.com
- What We Do - http://honestly.red-badger.com/what-we-do (is currently case-studies)
- About Us - https://red-badger.com/about-us/
- Blog - http://red-badger.com/blog/
- Events - https://red-badger.com/events/

<img width="1424" alt="screen shot 2016-10-19 at 10 19 23" src="https://cloud.githubusercontent.com/assets/8049847/19512800/8898423e-95e5-11e6-83fc-dec31802f2f9.png">
- Stat boxes - Relevant case study (ie https://red-badger.com/our-work/case-study/sky-cms/)
- See More of our work - https://red-badger.com/our-work/

<img width="861" alt="screen shot 2016-10-19 at 10 20 35" src="https://cloud.githubusercontent.com/assets/8049847/19513084/95ae05a2-95e6-11e6-8111-5e72b7d0850a.png">
- How We Work (this button should be renamed to "what we do") - http://honestly.red-badger.com/what-we-do (is currently case-studies)

<img width="1191" alt="screen shot 2016-10-19 at 10 28 44" src="https://cloud.githubusercontent.com/assets/8049847/19513248/2dce0c60-95e7-11e6-84f0-ad0b4d397fb3.png">
- More about the tech -  https://red-badger.com/services/technology/

<img width="1192" alt="screen shot 2016-10-19 at 10 33 06" src="https://cloud.githubusercontent.com/assets/8049847/19513324/73a1602a-95e7-11e6-9a3e-9b4cbd902407.png">
- Blog titles - Link to the quoted blog (ie http://red-badger.com/blog/2016/06/22/docker-and-assets-and-rails-oh-my/)
- Read our blog - http://red-badger.com/blog/

<img width="177" alt="screen shot 2016-10-19 at 10 34 12" src="https://cloud.githubusercontent.com/assets/8049847/19513377/9ba6b4da-95e7-11e6-9dac-5e72fabebd76.png">
- Home - http://honestly.red-badger.com
- About Us - https://red-badger.com/about-us/
- What We Do - http://honestly.red-badger.com/what-we-do (is currently case-studies)
- Blog - http://red-badger.com/blog/
- Events - https://red-badger.com/events/
- Jobs - https://red-badger.com/about-us/join-us/

**Comment by asavin** [comment]
Needs verifying with @Roisi

**Comment by Roisi** [comment]
all looking good now! Thanks @asavin
