### ISSUE TITLE
Typography sweep

### ISSUE THREAD

**Issue by clmntnbrn** [redbadger/website-honestly#93]
We will do a full typography sweep but just leaving this here as a reminder...
- [ ] Georgia Bold should be the fallback for headings

**Comment by Roisi** [comment]
@clmntnbrn are you still planning on this? Doing a clean up of issues

**Comment by clmntnbrn** [comment]
I'd completely forgotten... happy to but not sure I'm the best person as I didn't design or work on it (really), @sarigriffiths what do you think?

**Comment by dpiatek** [comment]
Should be done as part of typography cleanup card (which will review if the above recommendation needs to be applied)
