### ISSUE TITLE
GTM content page: Styling differences in footer compared to main website

### ISSUE THREAD

**Issue by samsmithyeah** [redbadger/website-honestly#957]
The footer in the GTM content page has a few small styling differences when compared to the main website:

GTM content page:
![Screenshot 2021-04-08 at 10 46 08](https://user-images.githubusercontent.com/22592849/114007820-938dff00-9859-11eb-99b9-06958cd3e281.png)

Main website for reference:
![Screenshot 2021-04-08 at 10 46 23](https://user-images.githubusercontent.com/22592849/114007973-b5878180-9859-11eb-9b7f-468a1693f76e.png)

### Expected Behaviour

Should look pretty much the same

### Actual Behaviour

In reference to the highlighted points in the screenshot above:

1. The spacing between nav items is smaller in the GTM content page
2. The spacing between characters in the phone number needs fixing
3. The font weight in the address needs fixing to match the main website
4. The font weight in the disclaimer needs fixing to match the main website

Tested in macOS Chrome

**Comment by samsmithyeah** [comment]
Sorry this is a bit of a big bug actually. I can split out if preferred.

**Comment by SiAshbery** [comment]
👍

**Comment by samsmithyeah** [comment]
@SiAshbery Since this change, the `We use cookies on our website. For more information, view our privacy policy and website T&C's.` text seems to be missing

**Comment by SiAshbery** [comment]
> @SiAshbery Since this change, the `We use cookies on our website. For more information, view our privacy policy and website T&C's.` text seems to be missing

Good catch! re-added.

**Comment by samsmithyeah** [comment]
This is now fixed. There are a few subtle differences in the spacing in the footer still, but we have deemed it Good Enough™️.
