### ISSUE TITLE
GTM content page: Top nav breakpoint funkiness (695px)

### ISSUE THREAD

**Issue by samsmithyeah** [redbadger/website-honestly#958]
The top nav is cutoff and doesn't snap to mobile view at screen widths of around 695px:

![Screenshot 2021-04-08 at 11 06 48](https://user-images.githubusercontent.com/22592849/114008996-ae14a800-985a-11eb-8491-5cfa85a3df35.png)

### Expected Behaviour

Should snap to mobile nav

### Actual Behaviour

Cuts off nav items

### Steps to Reproduce

Resize window to ~695px

### OS/Browsers Affected

Tested in macOS Chrome

**Comment by SiAshbery** [comment]
Fixed, brought in line with how it works on the main site. Still doesn't look the best at that specific size but it is readable and consistent.

**Comment by samsmithyeah** [comment]
Verified fixed
