### ISSUE TITLE
GTM content page: Mobile nav is missing 'Experience us' item

### ISSUE THREAD

**Issue by samsmithyeah** [redbadger/website-honestly#959]
The GTM content page doesn't have the `Experience us` nav item that is present in the same nav on the main website (main on the left, GTM page on the right):

![Screenshot 2021-04-08 at 11 10 33](https://user-images.githubusercontent.com/22592849/114010705-524b1e80-985c-11eb-9298-c9d0ffe9e793.png)

### Expected Behaviour

They should match

### Actual Behaviour

They don't match

**Comment by SiAshbery** [comment]
Added

**Comment by samsmithyeah** [comment]
Verified fixed
