### ISSUE TITLE
GTM content page: External links should default to opening in new tab

### ISSUE THREAD

**Issue by samsmithyeah** [redbadger/website-honestly#960]
Not totally sure if this is a legit bug or just a content issue

### Expected Behaviour

External links should default to opening in new tab

### Actual Behaviour

All links open in the current tab

### Steps to Reproduce

Click on an external link

**Comment by SiAshbery** [comment]
Fixed for the navs, links in the body are handled in the content editor. We are adding the final content later today so I will let whoever is editing know links should open in a new tab.

**Comment by samsmithyeah** [comment]
All links (even ones that take you to the RB website) are now opening in a new tab. @SiAshbery to check that this is the desired behaviour.

**Comment by SiAshbery** [comment]
Reverted back, all nav links should now open in the same window.

**Comment by samsmithyeah** [comment]
@SiAshbery is this confirmed to be the desired behaviour?

**Comment by SiAshbery** [comment]
@samsmithyeah It is.
