### ISSUE TITLE
GTM content page: Footer jumps when hovering over some links

### ISSUE THREAD

**Issue by samsmithyeah** [redbadger/website-honestly#961]
https://user-images.githubusercontent.com/22592849/114012391-2cbf1480-985e-11eb-9b7a-5551ae582329.mov

### Expected Behaviour

Shouldn't jump

### Actual Behaviour

Hovering over the email address and phone number in the footer causes some jumping (see screen recording above)

tested in macOS chrome

**Comment by SiAshbery** [comment]
Added transparent border as default to prevent hover effect causing jumps

**Comment by samsmithyeah** [comment]
Verified fixed. Although may have caused #965.
