### ISSUE TITLE
GTM content page: Main header is cut off at some widths

### ISSUE THREAD

**Issue by samsmithyeah** [redbadger/website-honestly#963]
At some screen widths (~1030px and ~690px) the main header is being cut off:

1030px:
![Screenshot 2021-04-08 at 12 19 01](https://user-images.githubusercontent.com/22592849/114018233-eb7e3300-9864-11eb-9707-fc027d214bc0.png)

690px:
![Screenshot 2021-04-08 at 12 19 36](https://user-images.githubusercontent.com/22592849/114018246-ede08d00-9864-11eb-9f60-699220f710e6.png)

### Expected Behaviour

Should be nice and responsive

### Actual Behaviour

Doesn't cope with some widths

**Comment by SiAshbery** [comment]
Adjusted so it should conform to page width properly.

**Comment by samsmithyeah** [comment]
Verified fixed
