### ISSUE TITLE
GTM content page: Wrapping issue with phone number in footer (firefox only)

### ISSUE THREAD

**Issue by samsmithyeah** [redbadger/website-honestly#965]
This now happens on firefox:

![Screenshot 2021-04-14 at 13 31 09](https://user-images.githubusercontent.com/22592849/114710657-e79b5680-9d25-11eb-9b68-3d2aec714b76.png)

Not sure which fix broke it.

**Comment by SiAshbery** [comment]
fixed

**Comment by samsmithyeah** [comment]
Verified fixed
