### ISSUE TITLE
GTM content page: Body text looks quite narrow at around 700px width

### ISSUE THREAD

**Issue by samsmithyeah** [redbadger/website-honestly#966]
Maybe this is intended, but it looks quite squashed to me (window widths around 700px):

![Screenshot 2021-04-14 at 13 42 31](https://user-images.githubusercontent.com/22592849/114711883-6218a600-9d27-11eb-8a1a-5de26bf2e8bd.png)

**Comment by SiAshbery** [comment]
Bumped the breakpoint for the body width up to large screen

**Comment by samsmithyeah** [comment]
Verified fixed
