### ISSUE TITLE
GTM content page: Disclaimer text wrapping wrong on IE11

### ISSUE THREAD

**Issue by samsmithyeah** [redbadger/website-honestly#967]
This is happening on IE11:

![Screenshot 2021-04-16 at 11 26 32](https://user-images.githubusercontent.com/22592849/115011526-a0889f00-9ea6-11eb-8000-9807e71ca683.png)

### Expected Behaviour

Should go full width

**Comment by SiAshbery** [comment]
Changed the display mode, should be fixed

**Comment by samsmithyeah** [comment]
Verified fixed
