### ISSUE TITLE
GTM content page: Font wrong on IE11

### ISSUE THREAD

**Issue by samsmithyeah** [redbadger/website-honestly#968]
The font should be Sentinel but is loading Georgia instead on IE11.

**Comment by SiAshbery** [comment]
![ie](https://user-images.githubusercontent.com/26712439/115207354-6cee8480-a0f3-11eb-9c07-9e4aff1dac19.png)
For reference

**Comment by SiAshbery** [comment]
See previous font fix.

**Comment by samsmithyeah** [comment]
@SiAshbery This is fixed in the page body but not in the footer:

![Screenshot 2021-04-26 at 16 32 45](https://user-images.githubusercontent.com/22592849/116109946-2bd71100-a6ad-11eb-962f-28918959f39a.png)

If you'd prefer me to log this as a new issue let me know.

**Comment by samsmithyeah** [comment]
Verified fixed
