### ISSUE TITLE
Landing page: content overlaps at some screen widths (eg 850px)

### ISSUE THREAD

**Issue by samsmithyeah** [redbadger/website-honestly#971]
![Screenshot 2021-04-22 at 10 23 43](https://user-images.githubusercontent.com/22592849/115690413-f2bd3a80-a354-11eb-8e1c-45d2d4282221.png)

### Expected Behaviour

Shouldn't overlap

**Comment by SiAshbery** [comment]
Previous fix for making sure the tiles are visually separated should address this.

**Comment by samsmithyeah** [comment]
Verified fixed
