### ISSUE TITLE
Landing page: 'Benefits' images should be on separate tiles

### ISSUE THREAD

**Issue by samsmithyeah** [redbadger/website-honestly#972]
'Benefits' images should be on separate tiles but they are currently all together. 

### Expected Behaviour
This is the design:
![Screenshot 2021-04-22 at 10 32 21](https://user-images.githubusercontent.com/22592849/115691822-4d0acb00-a356-11eb-9c1e-69ab78cc5a8b.png)

### Actual Behaviour
This is reality:
![Screenshot 2021-04-22 at 10 32 00](https://user-images.githubusercontent.com/22592849/115691842-5136e880-a356-11eb-8013-d70aef735e59.png)

**Comment by samsmithyeah** [comment]
Just realised they are on separate tiles but this is only visible when window is wider than about 1400px

**Comment by SiAshbery** [comment]
Changed the breakpoints to better accommodate the design

**Comment by samsmithyeah** [comment]
Verified fixed
