### ISSUE TITLE
GTM content page: Spacing not quite right on bullet paragraphs

### ISSUE THREAD

**Issue by samsmithyeah** [redbadger/website-honestly#973]
### Expected Behaviour
Design:
![Screenshot 2021-04-22 at 10 36 10](https://user-images.githubusercontent.com/22592849/115692239-b2f75280-a356-11eb-9706-c458f0084942.png)

### Actual Behaviour
Reality:
![Screenshot 2021-04-22 at 10 36 17](https://user-images.githubusercontent.com/22592849/115692279-be4a7e00-a356-11eb-9fa7-83659acec902.png)

**Comment by SiAshbery** [comment]
fixed

**Comment by samsmithyeah** [comment]
Verified fixed
