### ISSUE TITLE
Landing page: Correct font not loading on Firefox and IE11

### ISSUE THREAD

**Issue by samsmithyeah** [redbadger/website-honestly#975]
Should load Sentinal but falling back to Georgia instead:
![Screenshot 2021-04-22 at 15 13 37](https://user-images.githubusercontent.com/22592849/115729461-565b5e00-a37d-11eb-83c6-7719e895140a.png)

### OS/Browsers Affected

Firefox and IE11

**Comment by SiAshbery** [comment]
Error was caused by IE11 not being able to parse the base64 version of the font. 

Loaded now fonts in and it seems to be working now.

**Comment by samsmithyeah** [comment]
@SiAshbery I now get this error in the console - could be related to this fix?

![Screenshot 2021-04-26 at 16 53 45](https://user-images.githubusercontent.com/22592849/116112986-fe3f9700-a6af-11eb-94e0-2fb49cc58bc8.png)

**Comment by samsmithyeah** [comment]
@SiAshbery looks like this bug is fixed on firefox but not on IE11

**Comment by samsmithyeah** [comment]
Verified fixed
