### ISSUE TITLE
Landing page: Footer layout wrong on IE11

### ISSUE THREAD

**Issue by samsmithyeah** [redbadger/website-honestly#976]
![Screenshot 2021-04-22 at 15 21 06](https://user-images.githubusercontent.com/22592849/115730909-9b33c480-a37e-11eb-96e3-ea89a9e322cd.png)

### Expected Behaviour
Should look like this:
![Screenshot 2021-04-22 at 15 23 07](https://user-images.githubusercontent.com/22592849/115730984-abe43a80-a37e-11eb-80d4-27718d5a5510.png)

### OS/Browsers Affected
IE11

**Comment by SiAshbery** [comment]
Added additional styles to support IE11

**Comment by samsmithyeah** [comment]
Verified fixed
