### ISSUE TITLE
Landing page: Weird scroll bars in form on IE11

### ISSUE THREAD

**Issue by samsmithyeah** [redbadger/website-honestly#977]
![Screenshot 2021-04-22 at 15 21 33](https://user-images.githubusercontent.com/22592849/115731230-dfbf6000-a37e-11eb-8bf6-8fb2a9a636e2.png)

### Expected Behaviour

No scroll bars

### OS/Browsers Affected

IE11

**Comment by SiAshbery** [comment]
Turns out it's not a scroll bar. There's an inhereted style that gives it a solid black background.

Removed that style should work now.

**Comment by samsmithyeah** [comment]
Oh yeah silly me, of course it's not a scroll bar 🤦 
Anyway, verified fixed
